<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Using condition-event link (CLNK) file | MEPS tutorials</title>
  <meta name="description" content="This is a collection of MEPS tutorials." />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Using condition-event link (CLNK) file | MEPS tutorials" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a collection of MEPS tutorials." />
  <meta name="github-repo" content="mbounthavong/MEPS_tutorials_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Using condition-event link (CLNK) file | MEPS tutorials" />
  
  <meta name="twitter:description" content="This is a collection of MEPS tutorials." />
  

<meta name="author" content="Mark Bounthavong" />


<meta name="date" content="2024-01-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="weights.html"/>
<link rel="next" href="trends.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MEPS Tutorials Collection</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#book-link"><i class="fa fa-check"></i>Book link</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#table-of-contents"><i class="fa fa-check"></i>Table of contents</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Loading MEPS data into R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#meps-data"><i class="fa fa-check"></i><b>1.2</b> MEPS Data</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#load-meps-data-into-r"><i class="fa fa-check"></i><b>1.3</b> Load MEPS data into R</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#conclusions"><i class="fa fa-check"></i><b>1.4</b> Conclusions</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#acknowledgements"><i class="fa fa-check"></i><b>1.5</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="merging.html"><a href="merging.html"><i class="fa fa-check"></i><b>2</b> Merging files</a>
<ul>
<li class="chapter" data-level="2.1" data-path="merging.html"><a href="merging.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="merging.html"><a href="merging.html#load-meps-data"><i class="fa fa-check"></i><b>2.2</b> Load MEPS data</a></li>
<li class="chapter" data-level="2.3" data-path="merging.html"><a href="merging.html#merge-meps-data"><i class="fa fa-check"></i><b>2.3</b> Merge MEPS data</a></li>
<li class="chapter" data-level="2.4" data-path="merging.html"><a href="merging.html#reduce-dataframe-to-a-few-variables"><i class="fa fa-check"></i><b>2.4</b> Reduce dataframe to a few variables</a></li>
<li class="chapter" data-level="2.5" data-path="merging.html"><a href="merging.html#add-an-indicator-for-a-specific-icd10-diagnostic-code"><i class="fa fa-check"></i><b>2.5</b> Add an indicator for a specific ICD10 diagnostic code</a></li>
<li class="chapter" data-level="2.6" data-path="merging.html"><a href="merging.html#collapse-dataframe-to-a-single-unique-patient"><i class="fa fa-check"></i><b>2.6</b> Collapse dataframe to a single unique patient</a></li>
<li class="chapter" data-level="2.7" data-path="merging.html"><a href="merging.html#conclusions-1"><i class="fa fa-check"></i><b>2.7</b> Conclusions</a></li>
<li class="chapter" data-level="2.8" data-path="merging.html"><a href="merging.html#acknowledgements-1"><i class="fa fa-check"></i><b>2.8</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="weights.html"><a href="weights.html"><i class="fa fa-check"></i><b>3</b> Applying weights</a>
<ul>
<li class="chapter" data-level="3.1" data-path="weights.html"><a href="weights.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="weights.html"><a href="weights.html#types-of-weights"><i class="fa fa-check"></i><b>3.2</b> Types of weights</a></li>
<li class="chapter" data-level="3.3" data-path="weights.html"><a href="weights.html#loading-the-data"><i class="fa fa-check"></i><b>3.3</b> Loading the data</a></li>
<li class="chapter" data-level="3.4" data-path="weights.html"><a href="weights.html#perform-descriptive-analysis"><i class="fa fa-check"></i><b>3.4</b> Perform descriptive analysis</a></li>
<li class="chapter" data-level="3.5" data-path="weights.html"><a href="weights.html#conclusions-2"><i class="fa fa-check"></i><b>3.5</b> Conclusions</a></li>
<li class="chapter" data-level="3.6" data-path="weights.html"><a href="weights.html#acknowledgements-2"><i class="fa fa-check"></i><b>3.6</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="clnk.html"><a href="clnk.html"><i class="fa fa-check"></i><b>4</b> Using condition-event link (<code>CLNK</code>) file</a>
<ul>
<li class="chapter" data-level="4.1" data-path="clnk.html"><a href="clnk.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="clnk.html"><a href="clnk.html#motivating-example---migraine-specific-expenditures"><i class="fa fa-check"></i><b>4.2</b> Motivating example - Migraine-specific expenditures</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="clnk.html"><a href="clnk.html#part-1---setup"><i class="fa fa-check"></i><b>4.2.1</b> Part 1 - Setup</a></li>
<li class="chapter" data-level="4.2.2" data-path="clnk.html"><a href="clnk.html#part-2---migraine-specific-office-based-expenditures"><i class="fa fa-check"></i><b>4.2.2</b> Part 2 - Migraine-specific office-based expenditures</a></li>
<li class="chapter" data-level="4.2.3" data-path="clnk.html"><a href="clnk.html#part-3---migraine-specific-inpatient-expenditures"><i class="fa fa-check"></i><b>4.2.3</b> Part 3 - Migraine-specific inpatient expenditures</a></li>
<li class="chapter" data-level="4.2.4" data-path="clnk.html"><a href="clnk.html#part-4---combine-office-based-and-inpatient-expenditure-files"><i class="fa fa-check"></i><b>4.2.4</b> Part 4 - Combine office-based and inpatient expenditure files</a></li>
<li class="chapter" data-level="4.2.5" data-path="clnk.html"><a href="clnk.html#part-5---descriptive-analysis-using-survey-weights"><i class="fa fa-check"></i><b>4.2.5</b> Part 5 - Descriptive analysis using survey weights</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="clnk.html"><a href="clnk.html#conclusions-3"><i class="fa fa-check"></i><b>4.3</b> Conclusions</a></li>
<li class="chapter" data-level="4.4" data-path="clnk.html"><a href="clnk.html#acknowledgements-3"><i class="fa fa-check"></i><b>4.4</b> Acknowledgements</a></li>
<li class="chapter" data-level="4.5" data-path="clnk.html"><a href="clnk.html#work-in-progress"><i class="fa fa-check"></i><b>4.5</b> Work in progress</a></li>
<li class="chapter" data-level="4.6" data-path="clnk.html"><a href="clnk.html#disclaimers"><i class="fa fa-check"></i><b>4.6</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="trends.html"><a href="trends.html"><i class="fa fa-check"></i><b>5</b> Simple trend analysis with linear models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="trends.html"><a href="trends.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="trends.html"><a href="trends.html#motivating-example"><i class="fa fa-check"></i><b>5.2</b> Motivating example</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="trends.html"><a href="trends.html#loading-the-libraries"><i class="fa fa-check"></i><b>5.2.1</b> Loading the libraries</a></li>
<li class="chapter" data-level="5.2.2" data-path="trends.html"><a href="trends.html#loading-data-into-the-r-environment"><i class="fa fa-check"></i><b>5.2.2</b> Loading data into the R environment</a></li>
<li class="chapter" data-level="5.2.3" data-path="trends.html"><a href="trends.html#download-the-linkage-file"><i class="fa fa-check"></i><b>5.2.3</b> Download the linkage file</a></li>
<li class="chapter" data-level="5.2.4" data-path="trends.html"><a href="trends.html#creating-the-pooled-data-file"><i class="fa fa-check"></i><b>5.2.4</b> Creating the pooled data file</a></li>
<li class="chapter" data-level="5.2.5" data-path="trends.html"><a href="trends.html#merging-with-pooled-survey-primary-sampling-strata-and-unit"><i class="fa fa-check"></i><b>5.2.5</b> Merging with pooled survey primary sampling strata and unit</a></li>
<li class="chapter" data-level="5.2.6" data-path="trends.html"><a href="trends.html#create-factor-variables"><i class="fa fa-check"></i><b>5.2.6</b> Create factor variables</a></li>
<li class="chapter" data-level="5.2.7" data-path="trends.html"><a href="trends.html#set-the-survey-options"><i class="fa fa-check"></i><b>5.2.7</b> Set the survey options</a></li>
<li class="chapter" data-level="5.2.8" data-path="trends.html"><a href="trends.html#trend-analysis---plot-the-total-healthcare-costs-by-sex-across-time"><i class="fa fa-check"></i><b>5.2.8</b> Trend analysis - Plot the total healthcare costs by sex across time</a></li>
<li class="chapter" data-level="5.2.9" data-path="trends.html"><a href="trends.html#regression-model"><i class="fa fa-check"></i><b>5.2.9</b> Regression model</a></li>
<li class="chapter" data-level="5.2.10" data-path="trends.html"><a href="trends.html#average-marginal-effects-between-males-and-females-at-each-year"><i class="fa fa-check"></i><b>5.2.10</b> Average marginal effects between males and females at each year</a></li>
<li class="chapter" data-level="5.2.11" data-path="trends.html"><a href="trends.html#average-marginal-effects-between-years-for-males-and-females"><i class="fa fa-check"></i><b>5.2.11</b> Average marginal effects between years for males and females</a></li>
<li class="chapter" data-level="5.2.12" data-path="trends.html"><a href="trends.html#plot-the-average-marginal-effects"><i class="fa fa-check"></i><b>5.2.12</b> Plot the average marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="trends.html"><a href="trends.html#conclusions-4"><i class="fa fa-check"></i><b>5.3</b> Conclusions</a></li>
<li class="chapter" data-level="5.4" data-path="trends.html"><a href="trends.html#acknowledgements-4"><i class="fa fa-check"></i><b>5.4</b> Acknowledgements</a></li>
<li class="chapter" data-level="5.5" data-path="trends.html"><a href="trends.html#work-in-progress-1"><i class="fa fa-check"></i><b>5.5</b> Work in progress</a></li>
<li class="chapter" data-level="5.6" data-path="trends.html"><a href="trends.html#disclaimers-1"><i class="fa fa-check"></i><b>5.6</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="itsa.html"><a href="itsa.html"><i class="fa fa-check"></i><b>6</b> Interrupted time series analysis (ITSA) with R: A short tutorial</a>
<ul>
<li class="chapter" data-level="6.1" data-path="itsa.html"><a href="itsa.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="itsa.html"><a href="itsa.html#motivating-example---total-healthcare-costs-from-2016-to-2021-by-sex"><i class="fa fa-check"></i><b>6.2</b> Motivating example - Total Healthcare Costs from 2016 to 2021 by sex</a></li>
<li class="chapter" data-level="6.3" data-path="itsa.html"><a href="itsa.html#interrupted-time-series-analysis-design"><i class="fa fa-check"></i><b>6.3</b> Interrupted Time Series Analysis Design</a></li>
<li class="chapter" data-level="6.4" data-path="itsa.html"><a href="itsa.html#set-up-the-survey-options"><i class="fa fa-check"></i><b>6.4</b> Set up the survey options</a></li>
<li class="chapter" data-level="6.5" data-path="itsa.html"><a href="itsa.html#descriptive-analysis"><i class="fa fa-check"></i><b>6.5</b> Descriptive analysis</a></li>
<li class="chapter" data-level="6.6" data-path="itsa.html"><a href="itsa.html#linear-regression-model"><i class="fa fa-check"></i><b>6.6</b> Linear regression model</a></li>
<li class="chapter" data-level="6.7" data-path="itsa.html"><a href="itsa.html#plot"><i class="fa fa-check"></i><b>6.7</b> Plot</a></li>
<li class="chapter" data-level="6.8" data-path="itsa.html"><a href="itsa.html#parallel-trends-assumption"><i class="fa fa-check"></i><b>6.8</b> Parallel trends assumption</a></li>
<li class="chapter" data-level="6.9" data-path="itsa.html"><a href="itsa.html#additional-estimations"><i class="fa fa-check"></i><b>6.9</b> Additional estimations</a></li>
<li class="chapter" data-level="6.10" data-path="itsa.html"><a href="itsa.html#issues-with-the-current-model"><i class="fa fa-check"></i><b>6.10</b> Issues with the current model</a></li>
<li class="chapter" data-level="6.11" data-path="itsa.html"><a href="itsa.html#workaround-using-a-linear-spline-model"><i class="fa fa-check"></i><b>6.11</b> Workaround using a linear spline model</a></li>
<li class="chapter" data-level="6.12" data-path="itsa.html"><a href="itsa.html#differences-in-level-immediately-after-implementation-of-the-intervention"><i class="fa fa-check"></i><b>6.12</b> Differences in level immediately after implementation of the intervention</a></li>
<li class="chapter" data-level="6.13" data-path="itsa.html"><a href="itsa.html#difference-in-differences-estimation"><i class="fa fa-check"></i><b>6.13</b> Difference-in-differences estimation</a></li>
<li class="chapter" data-level="6.14" data-path="itsa.html"><a href="itsa.html#putting-it-all-together"><i class="fa fa-check"></i><b>6.14</b> Putting it all together</a></li>
<li class="chapter" data-level="6.15" data-path="itsa.html"><a href="itsa.html#conclusions-5"><i class="fa fa-check"></i><b>6.15</b> Conclusions</a></li>
<li class="chapter" data-level="6.16" data-path="itsa.html"><a href="itsa.html#acknowledgements-5"><i class="fa fa-check"></i><b>6.16</b> Acknowledgements</a></li>
<li class="chapter" data-level="6.17" data-path="itsa.html"><a href="itsa.html#work-in-progress-2"><i class="fa fa-check"></i><b>6.17</b> Work in progress</a></li>
<li class="chapter" data-level="6.18" data-path="itsa.html"><a href="itsa.html#disclaimers-2"><i class="fa fa-check"></i><b>6.18</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="notes.html"><a href="notes.html"><i class="fa fa-check"></i><b>7</b> Helpful Notes</a>
<ul>
<li class="chapter" data-level="7.1" data-path="notes.html"><a href="notes.html#introduction-6"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="notes.html"><a href="notes.html#meps-file-names"><i class="fa fa-check"></i><b>7.1.1</b> 1. MEPS file names</a></li>
<li class="chapter" data-level="7.1.2" data-path="notes.html"><a href="notes.html#expenditure-categories"><i class="fa fa-check"></i><b>7.1.2</b> 2. Expenditure categories</a></li>
<li class="chapter" data-level="7.1.3" data-path="notes.html"><a href="notes.html#sources-of-payments"><i class="fa fa-check"></i><b>7.1.3</b> 3. Sources of payments</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="notes.html"><a href="notes.html#references"><i class="fa fa-check"></i><b>7.2</b> References</a></li>
<li class="chapter" data-level="7.3" data-path="notes.html"><a href="notes.html#disclaimer"><i class="fa fa-check"></i><b>7.3</b> Disclaimer</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MEPS tutorials</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="clnk" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Using condition-event link (<code>CLNK</code>) file<a href="clnk.html#clnk" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-3" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Introduction<a href="clnk.html#introduction-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Agency for Healthcare Research and Quality (AHRQ) Medical Expenditure Panel Survey (MEPS) categorizes expenditures into different components. Healthcare expenditures (e.g., costs and utilization) are provided for each individual respondent in MEPS. For instance, healthcare expenditures are categorized as total healthcare expenditures (<code>totexp21</code>), office-based expenditures (<code>obvexp21</code>), outpatient expenditures (<code>opvexp21</code>), inpatient expenditures (<code>iptexp21</code>), and prescription expenditures (<code>rxexp21</code>) to name a few. Reading the long but detailed <a href="https://meps.ahrq.gov/data_stats/download_data/pufs/h233/h233doc.shtml">documentation</a> is a good way to learn more about the different expenditure categories. Moreover, you can also review <strong>Appendix 3</strong> of the documentation (see Figure below).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="Figure%204_1%20-%20Appendix%203.png" alt="MEPS Appendix 3 - Expenditure variables" width="100%" />
<p class="caption">
Figure 4.1: MEPS Appendix 3 - Expenditure variables
</p>
</div>
<p>These costs and utilization provide information about the annual expenditures associated with each category for each individual respondent. But this doesn’t provide <u>disease-specific expenditures</u>. For example, an individual may have an annual office-based visits healthcare cost of $10,000, but part of this costs may be due to a specific disease such as migraine. How much of the $10,000 is due to migraine-related office-based visits? One can answer this question using the <a href="https://meps.ahrq.gov/data_stats/download_data/pufs/h229i/h229idoc.shtml">condition-event link (<code>CLNK</code>) file</a>.</p>
<p>The <code>CLNK</code> file has a unique variable that can be used to link each record on the <a href="https://meps.ahrq.gov/data_stats/download_data_files_detail.jsp?cboPufNumber=HC-231">Medical Conditions file</a> with event files from the respective year (e.g., <code>HC-229D</code> through <code>HC-229H</code>). One of these event files that we’re interested in is the office-based event file (<code>HC-229G</code>). The <code>CLNK</code> file contains 6 variables:</p>
<ul>
<li><p><code>dupersid</code> - 10-digit unique identifier</p></li>
<li><p><code>condidx</code> - 13-digit unique identifier for a condition</p></li>
<li><p><code>evntidx</code> - 16-digit unique identifier for each event</p></li>
<li><p><code>clnkidx</code> - 29-digit unique identifier for each record; combines <code>condidx</code> and <code>evntidx</code></p></li>
<li><p><code>eventype</code> - indicates the type of event record (see Figure)</p></li>
<li><p><code>panel</code> - indicate the panel when the interview occurred</p></li>
</ul>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-35"></span>
<img src="Figure%204_2.png" alt="Type of event record (`eventype`)" width="100%" />
<p class="caption">
Figure 4.2: Type of event record (<code>eventype</code>)
</p>
</div>
<p>Using these files, we can acquire disease-specific expenditures from MEPS data, which may be important for those of us who are interested in these expenditures.</p>
</div>
<div id="motivating-example---migraine-specific-expenditures" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Motivating example - Migraine-specific expenditures<a href="clnk.html#motivating-example---migraine-specific-expenditures" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this motivating example, we will review how to use MEPS to find the office-based expenditures and inpatient expenditures specific to migraine.</p>
<div id="part-1---setup" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Part 1 - Setup<a href="clnk.html#part-1---setup" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will need to install several packages. The <a href="https://github.com/HHS-AHRQ/MEPS">AHRQ MEPS GitHub site</a> is a great source for documents, tutorials, codes, and updates. I learned a ton going through their exercises, and a lot of the code you’ll see in this tutorial come from those resources.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="clnk.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To install &quot;MEPS&quot; package in R, you need to do a couple of things.</span></span>
<span id="cb36-2"><a href="clnk.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 1: Install the &quot;devtools&quot; package. </span></span>
<span id="cb36-3"><a href="clnk.html#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;devtools&quot;)</span></span>
<span id="cb36-4"><a href="clnk.html#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="clnk.html#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="clnk.html#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 2: Install the &quot;MEPS&quot; package from the AHRQ MEPS GitHub site. </span></span>
<span id="cb36-7"><a href="clnk.html#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github(&quot;e-mitchell/meps_r_pkg/MEPS&quot;)</span></span>
<span id="cb36-8"><a href="clnk.html#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="clnk.html#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="clnk.html#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 3: Load the MEPS package</span></span>
<span id="cb36-11"><a href="clnk.html#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;MEPS&quot;</span>) <span class="do">## You need to load the library every time you restart R</span></span>
<span id="cb36-12"><a href="clnk.html#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="clnk.html#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 4: Load the other libraries</span></span>
<span id="cb36-14"><a href="clnk.html#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;survey&quot;</span>)</span>
<span id="cb36-15"><a href="clnk.html#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;foreign&quot;</span>)</span>
<span id="cb36-16"><a href="clnk.html#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb36-17"><a href="clnk.html#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;psych&quot;</span>)</span></code></pre></div>
<p>Next, we set the global options.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="clnk.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set global options</span></span>
<span id="cb37-2"><a href="clnk.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">survey.lonely.psu =</span> <span class="st">&quot;adjust&quot;</span>) <span class="co"># survey option for lonely PSUs</span></span>
<span id="cb37-3"><a href="clnk.html#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">dplyr.width =</span> <span class="cn">Inf</span>) <span class="co"># Columns are not truncated</span></span>
<span id="cb37-4"><a href="clnk.html#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">10</span>) <span class="co"># Do not use scientific notation for large number</span></span></code></pre></div>
<p>Once that’s done, we will download the data directly from the MEPS site using the <code>read_MEPS</code> function. There are two ways to do this:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="clnk.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are two ways to load data from AHRQ MEPS website:</span></span>
<span id="cb38-2"><a href="clnk.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="do">#### Method 1: Load data from AHRQ MEPS website</span></span>
<span id="cb38-3"><a href="clnk.html#cb38-3" aria-hidden="true" tabindex="-1"></a>hc2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h233&quot;</span>) <span class="co"># Full-year consolidated file</span></span>
<span id="cb38-4"><a href="clnk.html#cb38-4" aria-hidden="true" tabindex="-1"></a>ob2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h229g&quot;</span>) <span class="co"># Office-based visits</span></span>
<span id="cb38-5"><a href="clnk.html#cb38-5" aria-hidden="true" tabindex="-1"></a>inpat2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h229d&quot;</span>) <span class="co"># Inpatient stays</span></span>
<span id="cb38-6"><a href="clnk.html#cb38-6" aria-hidden="true" tabindex="-1"></a>cond2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h231&quot;</span>) <span class="co"># Medical conditions file</span></span>
<span id="cb38-7"><a href="clnk.html#cb38-7" aria-hidden="true" tabindex="-1"></a>clnk2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h229IF1&quot;</span>) <span class="co"># Condition-Event Link File (CLNK)</span></span>
<span id="cb38-8"><a href="clnk.html#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="clnk.html#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="clnk.html#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="do">#### Method 2: Load data from AHRQ MEPS website</span></span>
<span id="cb38-11"><a href="clnk.html#cb38-11" aria-hidden="true" tabindex="-1"></a>hc2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>) <span class="co"># Full-year consolidated file</span></span>
<span id="cb38-12"><a href="clnk.html#cb38-12" aria-hidden="true" tabindex="-1"></a>ob2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;OB&quot;</span>) <span class="co"># Office-based visits</span></span>
<span id="cb38-13"><a href="clnk.html#cb38-13" aria-hidden="true" tabindex="-1"></a>inpat2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;IP&quot;</span>) <span class="co"># Inpatient stays</span></span>
<span id="cb38-14"><a href="clnk.html#cb38-14" aria-hidden="true" tabindex="-1"></a>cond2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;COND&quot;</span>) <span class="co"># Medical conditions file</span></span>
<span id="cb38-15"><a href="clnk.html#cb38-15" aria-hidden="true" tabindex="-1"></a>clnk2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;CLNK&quot;</span>) <span class="co"># Condition-Event Link File (CLNK)</span></span></code></pre></div>
<p>After the data are loaded, you can change the column names from upper case to lower case.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="clnk.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Change column names to lowercase</span></span>
<span id="cb39-2"><a href="clnk.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2021))</span>
<span id="cb39-3"><a href="clnk.html#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ob2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(ob2021))</span>
<span id="cb39-4"><a href="clnk.html#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(inpat2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(inpat2021))</span>
<span id="cb39-5"><a href="clnk.html#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cond2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(cond2021))</span>
<span id="cb39-6"><a href="clnk.html#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(clnk2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(clnk2021))</span></code></pre></div>
<p>Each of these tables will have a lot of variables. To make things easier and cleaner, let’s reduce the size of the tables to only include the essential variables.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="clnk.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the variables of interest</span></span>
<span id="cb40-2"><a href="clnk.html#cb40-2" aria-hidden="true" tabindex="-1"></a>hc2021x <span class="ot">=</span> hc2021 <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="clnk.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dupersid, totexp21, obvexp21, iptexp21, perwt21f, varpsu, varstr, sex, racev1x)</span>
<span id="cb40-4"><a href="clnk.html#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="clnk.html#cb40-5" aria-hidden="true" tabindex="-1"></a>ob2021x <span class="ot">=</span> ob2021 <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="clnk.html#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dupersid, evntidx, eventrn, obdateyr, obdatemm, obxp21x, perwt21f, varpsu, varstr)</span>
<span id="cb40-7"><a href="clnk.html#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="clnk.html#cb40-8" aria-hidden="true" tabindex="-1"></a>inpat2021x <span class="ot">=</span> inpat2021 <span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="clnk.html#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dupersid, evntidx, eventrn, numnighx, ipxp21x, perwt21f, varpsu, varstr)</span>
<span id="cb40-10"><a href="clnk.html#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="clnk.html#cb40-11" aria-hidden="true" tabindex="-1"></a>cond2021x <span class="ot">=</span> cond2021 <span class="sc">%&gt;%</span></span>
<span id="cb40-12"><a href="clnk.html#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dupersid, condidx, icd10cdx, ccsr1x<span class="sc">:</span>ccsr3x)</span></code></pre></div>
<p>Next, we want identify migraine condition from the <code>cond2021x</code> file, which is the medical conditions file. The CCSR code for migraine is <code>NVS010</code> (note: the ICD10 code for migraine is <code>G42</code>, but we won’t need it for this example). There are three CCSR columns (<code>ccsr1x</code>, <code>ccsr2x</code>, <code>ccsr3x</code>), and we want to concatenate these into a new column called <code>all_CCSR</code> to isolate for migraine. You can find the list of CCSR codes in the <a href="https://github.com/HHS-AHRQ/MEPS/blob/master/Quick_Reference_Guides/meps_ccsr_conditions.csv">AHRQ MEPS site</a>.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="clnk.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">################################# NOTES ################################# </span></span>
<span id="cb41-2"><a href="clnk.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Use CLNK file to map condition with events</span></span>
<span id="cb41-3"><a href="clnk.html#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="do">## CCSR code: https://github.com/HHS-AHRQ/MEPS/blob/master/Quick_Reference_Guides/meps_ccsr_conditions.csv</span></span>
<span id="cb41-4"><a href="clnk.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="do">## CCSR code for migraine: NVS010</span></span>
<span id="cb41-5"><a href="clnk.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="do">## ICD10 code for migraine: G43</span></span>
<span id="cb41-6"><a href="clnk.html#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="do">######################################################################### </span></span>
<span id="cb41-7"><a href="clnk.html#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="clnk.html#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Restrict conditions to Migraine only from the conditions file</span></span>
<span id="cb41-9"><a href="clnk.html#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="do">### This creates a variable called &quot;all_CCSR&quot; which concatenates the CCSR columns</span></span>
<span id="cb41-10"><a href="clnk.html#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="do">### Then, filter() only selects rows with the &quot;NVS010&quot; text in the &quot;all_CCSR&quot; column</span></span>
<span id="cb41-11"><a href="clnk.html#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="do">### Finally, this gets saved into the &quot;migraine&quot; object.</span></span>
<span id="cb41-12"><a href="clnk.html#cb41-12" aria-hidden="true" tabindex="-1"></a>migraine <span class="ot">=</span> cond2021x <span class="sc">%&gt;%</span> </span>
<span id="cb41-13"><a href="clnk.html#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(<span class="st">&quot;all_CCSR&quot;</span>, ccsr1x<span class="sc">:</span>ccsr3x, <span class="at">remove =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb41-14"><a href="clnk.html#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">&quot;NVS010&quot;</span>, all_CCSR))</span>
<span id="cb41-15"><a href="clnk.html#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="clnk.html#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="clnk.html#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># View freq per diagnosis code type (Pretty nice code from AHRQ)</span></span>
<span id="cb41-18"><a href="clnk.html#cb41-18" aria-hidden="true" tabindex="-1"></a>migraine <span class="sc">%&gt;%</span> </span>
<span id="cb41-19"><a href="clnk.html#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(icd10cdx, ccsr1x, ccsr2x, ccsr3x) </span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   icd10cdx ccsr1x ccsr2x ccsr3x     n
##   &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt;
## 1 -15      NVS010 -1     -1        26
## 2 G43      NVS010 -1     -1       556
## 3 R51      NVS010 SYM010 -1       202</code></pre>
</div>
<div id="part-2---migraine-specific-office-based-expenditures" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Part 2 - Migraine-specific office-based expenditures<a href="clnk.html#part-2---migraine-specific-office-based-expenditures" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have our data files set up and prepared, we can begin to identify the migraine-specific office-based expenditures.</p>
<p>First, we want to isolate the office-based visits events from the <code>clnk2021</code> file. According to the figure above, <code>eventype == 1</code> is for office-based medical provider visit event. We will save these results into a new object called <code>ob_events</code>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="clnk.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">############################################</span></span>
<span id="cb43-2"><a href="clnk.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="do">## OUTPATIENT VISITS</span></span>
<span id="cb43-3"><a href="clnk.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="do">############################################</span></span>
<span id="cb43-4"><a href="clnk.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Select Office-based events from the CLNK file</span></span>
<span id="cb43-5"><a href="clnk.html#cb43-5" aria-hidden="true" tabindex="-1"></a>ob_events <span class="ot">=</span> clnk2021 <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="clnk.html#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(eventype <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Next, we want to merge the <code>ob_events</code> object with the <code>migraine</code> object, which contains the migraine-related conditions. We use an <code>inner_join</code>, which will only subset rows that matches between the two objects by <code>dupersid</code> and <code>condidx</code>. This will be saved as a new object called <code>migraine_lnk</code>.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="clnk.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge migraine diagnosis conditions file with office-based visit file</span></span>
<span id="cb44-2"><a href="clnk.html#cb44-2" aria-hidden="true" tabindex="-1"></a>migraine_lnk <span class="ot">=</span> <span class="fu">inner_join</span>(</span>
<span id="cb44-3"><a href="clnk.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  migraine, ob_events,</span>
<span id="cb44-4"><a href="clnk.html#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>, <span class="st">&quot;condidx&quot;</span>)</span>
<span id="cb44-5"><a href="clnk.html#cb44-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Since the <code>migraine_lnk</code> object has duplicate <code>dupersid</code> and <code>condidx</code>, we want to create an updated dataframe (<code>migraine_ob_distinct</code>) that contains unique rows of <code>dupersid</code>, <code>evntidx</code>, and <code>eventype</code>. AHRQ called this process “De-duplicate.” We will use this term in our exercise.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="clnk.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only DISTINCT office-based events (&quot;De-duplicate&quot;)</span></span>
<span id="cb45-2"><a href="clnk.html#cb45-2" aria-hidden="true" tabindex="-1"></a>migraine_ob_distinct <span class="ot">=</span> migraine_lnk <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="clnk.html#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(dupersid, evntidx, eventype)</span></code></pre></div>
<p>Then we merge the <code>migraine_ob_distinct</code> dataframe with the <code>ob2021x</code> dataframe using the <code>inner_join</code> function because we want to only include the rows that are in both dataframes. We use the <code>mutate</code> function to generate a new indicator variable called <code>migrane_ob_visit =1</code>. This will yield a dataframe that contains the office-based events specific for migraines.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="clnk.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge office-based file with distinct office-based CLNK event file</span></span>
<span id="cb46-2"><a href="clnk.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Use the inner_join() to merge ob2021x and migraine_lnk_distinct dataframes</span></span>
<span id="cb46-3"><a href="clnk.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="do">### Then create a new indicator variable called &quot;migraine_ob_visit = 1.&quot;</span></span>
<span id="cb46-4"><a href="clnk.html#cb46-4" aria-hidden="true" tabindex="-1"></a>ob_migraine <span class="ot">=</span> <span class="fu">inner_join</span>(</span>
<span id="cb46-5"><a href="clnk.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  ob2021x, migraine_ob_distinct) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="clnk.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">migraine_ob_visit =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Once that’s done, we can merge the <code>ob_migraine</code> dataframe with the Full-Year Consolidated (<code>hc2021x</code>) dataframe. We create two indiciator variables: <code>migraine_ob = 1</code> to capture the total number of migraine-specific office-based visits, and <code>fyc = 1</code> to indicate that this is the Full-Year Consolidated file that was merged.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="clnk.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge with full-year consolidated file</span></span>
<span id="cb47-2"><a href="clnk.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Use the full_join() to keep all the rows from both dataframes.</span></span>
<span id="cb47-3"><a href="clnk.html#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="do">### Then create a new object called hc2021_ob_migraine</span></span>
<span id="cb47-4"><a href="clnk.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="do">### &amp; a new indicator variable called &quot;migraine_ob = 1&quot;</span></span>
<span id="cb47-5"><a href="clnk.html#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="do">### &amp; another new indicator variable called &quot;fyc = 1.&quot;</span></span>
<span id="cb47-6"><a href="clnk.html#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="do">### Note: These are not unique rows (repeated dupersid)</span></span>
<span id="cb47-7"><a href="clnk.html#cb47-7" aria-hidden="true" tabindex="-1"></a>hc2021_ob_migraine <span class="ot">=</span> <span class="fu">full_join</span>(</span>
<span id="cb47-8"><a href="clnk.html#cb47-8" aria-hidden="true" tabindex="-1"></a>  ob_migraine <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">migraine_ob =</span> <span class="dv">1</span>),</span>
<span id="cb47-9"><a href="clnk.html#cb47-9" aria-hidden="true" tabindex="-1"></a>  hc2021x <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">fyc =</span> <span class="dv">1</span>))</span></code></pre></div>
<p>Since this dataframe (<code>hc2021_ob_migraine</code>) contains duplicate <code>dupersid</code>, we want to create a dataframe where each row reflects a unique <code>dupersid</code>. We can do this by using the <code>group_by</code> function on specific variables that we know are unique to an individual (<code>dupersid</code>, <code>varstr</code>, <code>varpsu</code>, and <code>perwt21f</code>). These are the unique identifier of the individual and their associated stratum and weight.</p>
<p>We also will summarize the migraine-specific utilization such as office-based visit costs (<code>obxp21x</code>) and the total sum of those visits (<code>migraine_ob_visit</code>).</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="clnk.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to person-level</span></span>
<span id="cb48-2"><a href="clnk.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="do">### We have to do the estimations for the person-level at this stage</span></span>
<span id="cb48-3"><a href="clnk.html#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="do">### We will estimate the total and mean values of the migraine-related expenditures</span></span>
<span id="cb48-4"><a href="clnk.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="do">### The &quot;migraine_ob&quot; will be used to create an indicator for migraine-related expenditures</span></span>
<span id="cb48-5"><a href="clnk.html#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="do">### Need to set NA -&gt; zero.</span></span>
<span id="cb48-6"><a href="clnk.html#cb48-6" aria-hidden="true" tabindex="-1"></a>per_migraine_ob <span class="ot">=</span> hc2021_ob_migraine <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="clnk.html#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dupersid, varstr, varpsu, perwt21f) <span class="sc">%&gt;%</span></span>
<span id="cb48-8"><a href="clnk.html#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb48-9"><a href="clnk.html#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgtotexp_tot               =</span> <span class="fu">mean</span>(totexp21),  <span class="co"># average total expenditure</span></span>
<span id="cb48-10"><a href="clnk.html#cb48-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp_ob                   =</span> <span class="fu">sum</span>(obxp21x),    <span class="co"># sum of migraine-specific office-based visits per person</span></span>
<span id="cb48-11"><a href="clnk.html#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgexp_obvexp               =</span> <span class="fu">mean</span>(obvexp21),  <span class="co"># average office-based visits per person</span></span>
<span id="cb48-12"><a href="clnk.html#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">totvisit_ob                 =</span> <span class="fu">sum</span>(migraine_ob_visit), <span class="co"># sum of migraine-specific office-based visits</span></span>
<span id="cb48-13"><a href="clnk.html#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgvisit_migraine_ob        =</span> <span class="fu">mean</span>(migraine_ob_visit), <span class="co"># average migraine-specific office-based visits</span></span>
<span id="cb48-14"><a href="clnk.html#cb48-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgvisit_migraine_visits_ob =</span> <span class="fu">mean</span>(migraine_ob), <span class="co"># average migraine-specific office-based visits</span></span>
<span id="cb48-15"><a href="clnk.html#cb48-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">migraine_ob                 =</span> <span class="fu">max</span>(migraine_ob)) <span class="sc">%&gt;%</span> <span class="co"># indicator for migraine-specific expenditures</span></span>
<span id="cb48-16"><a href="clnk.html#cb48-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">replace_na</span>(</span>
<span id="cb48-17"><a href="clnk.html#cb48-17" aria-hidden="true" tabindex="-1"></a>      <span class="fu">list</span>(<span class="at">totexp_ob =</span> <span class="dv">0</span>, <span class="at">totvisit_ob =</span> <span class="dv">0</span>, <span class="at">totvisit_migraine_ob =</span> <span class="dv">0</span>, <span class="at">avgvisit_migraine_ob =</span> <span class="dv">0</span>, <span class="at">avgvisit_migraine_visits_ob =</span> <span class="dv">0</span>, <span class="at">migraine_ob =</span> <span class="dv">0</span>)</span>
<span id="cb48-18"><a href="clnk.html#cb48-18" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>The above code chunk seems intimidating, but there are sensible reasons why it is written this way. See the Figure below for a visual explanation.</p>
<p>The <u>migraine-specific</u> office-based costs and visits are expenditures that are at the event level denoted by the event identifier <code>evntidx</code>. Costs like the total expenditures and office-based costs are at the individual level denoted by the individual identifier <code>dupersid</code>. Hence, you will see that at the event level, the <u>migraine-specific</u> office-based costs <code>obxp21x</code> differs by events (<code>evntidx</code>. Conversely, the office-based costs are the same by individual (<code>dupersid</code>).</p>
<p>We need to sum or add up the <u>migraine-specific</u> office-based costs for each individual so that we can collapse the rows. We want to do create a new dataframe where each row is a unique individual denoted by their individual identifier (<code>dupersid</code>) and corresponding survey weights (<code>varstr</code>, <code>varpsu</code>, <code>perwt21f</code>).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-48"></span>
<img src="Figure%204_3.png" alt="Visual explanation of the code chunk" width="100%" />
<p class="caption">
Figure 4.3: Visual explanation of the code chunk
</p>
</div>
<p>Once this step is completed, you can check to see that the number of rows from the new dataframe (<code>per_migraine_ob</code>) is equal to the number of rows from the Full-Year Consolidated file (<code>hc2021</code>). They should be equal.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="clnk.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="do">### QC: Should have the same number as the full-year consolidated file</span></span>
<span id="cb49-2"><a href="clnk.html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(per_migraine_ob) <span class="sc">==</span> <span class="fu">nrow</span>(hc2021)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Now that you’ve merged the migraine-specific office-based expenditures with the Full-Year Consolidated file, we can start on repeating this process for the <u>migraine-specific inpatient expenditures</u>.</p>
</div>
<div id="part-3---migraine-specific-inpatient-expenditures" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Part 3 - Migraine-specific inpatient expenditures<a href="clnk.html#part-3---migraine-specific-inpatient-expenditures" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The code for the migraine-specific inpatient expenditures is similar to the migraine-specific office-based expenditures so I won’t go through them step-by-step. However, there are several important differences.</p>
<p>First, the inpatient event type is <code>eventype == 4</code>, which needs to be included when you isolate the event types from the <code>clnk2021</code> file.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="clnk.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">############################################</span></span>
<span id="cb51-2"><a href="clnk.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="do">## INPATIENT STAYS</span></span>
<span id="cb51-3"><a href="clnk.html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="do">############################################</span></span>
<span id="cb51-4"><a href="clnk.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inpatient stays events</span></span>
<span id="cb51-5"><a href="clnk.html#cb51-5" aria-hidden="true" tabindex="-1"></a>inpat_events <span class="ot">=</span> clnk2021 <span class="sc">%&gt;%</span></span>
<span id="cb51-6"><a href="clnk.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(eventype <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb51-7"><a href="clnk.html#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="clnk.html#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># QC: Should only have EVENTYPE == 4</span></span>
<span id="cb51-9"><a href="clnk.html#cb51-9" aria-hidden="true" tabindex="-1"></a>inpat_events <span class="sc">%&gt;%</span></span>
<span id="cb51-10"><a href="clnk.html#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(eventype)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   eventype                          n
##   &lt;dbl+lbl&gt;                     &lt;int&gt;
## 1 4 [4 INPATIENT HOSPITAL STAY]  3167</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="clnk.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge migraine diagnosis file with inpatient stays file</span></span>
<span id="cb53-2"><a href="clnk.html#cb53-2" aria-hidden="true" tabindex="-1"></a>migraine_lnk_inpat <span class="ot">=</span> <span class="fu">inner_join</span>(</span>
<span id="cb53-3"><a href="clnk.html#cb53-3" aria-hidden="true" tabindex="-1"></a>  migraine, inpat_events,</span>
<span id="cb53-4"><a href="clnk.html#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>, <span class="st">&quot;condidx&quot;</span>)</span>
<span id="cb53-5"><a href="clnk.html#cb53-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-6"><a href="clnk.html#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="clnk.html#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only DISTINCT events (&quot;De-duplicate&quot;)</span></span>
<span id="cb53-8"><a href="clnk.html#cb53-8" aria-hidden="true" tabindex="-1"></a>migraine_inpat_distinct <span class="ot">=</span> migraine_lnk_inpat <span class="sc">%&gt;%</span></span>
<span id="cb53-9"><a href="clnk.html#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(dupersid, evntidx, eventype)</span>
<span id="cb53-10"><a href="clnk.html#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="clnk.html#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="clnk.html#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge inpatient stays file with distinct migraine-specific inpatient stays file</span></span>
<span id="cb53-13"><a href="clnk.html#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="do">### Use the inner_join() to merge ob2021x and migraine_inpat_distinct dataframes</span></span>
<span id="cb53-14"><a href="clnk.html#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="do">### Then create a new indicator variable called &quot;migraine_inpat_stays = 1.&quot;</span></span>
<span id="cb53-15"><a href="clnk.html#cb53-15" aria-hidden="true" tabindex="-1"></a>inpat_migraine <span class="ot">=</span> <span class="fu">inner_join</span>(</span>
<span id="cb53-16"><a href="clnk.html#cb53-16" aria-hidden="true" tabindex="-1"></a>  inpat2021x, migraine_inpat_distinct) <span class="sc">%&gt;%</span></span>
<span id="cb53-17"><a href="clnk.html#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">migraine_inpat_stays =</span> <span class="dv">1</span>)</span>
<span id="cb53-18"><a href="clnk.html#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="clnk.html#cb53-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-20"><a href="clnk.html#cb53-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge with full-year consolidated file</span></span>
<span id="cb53-21"><a href="clnk.html#cb53-21" aria-hidden="true" tabindex="-1"></a><span class="do">### Use the full_join() to keep all the rows from both dataframes.</span></span>
<span id="cb53-22"><a href="clnk.html#cb53-22" aria-hidden="true" tabindex="-1"></a><span class="do">### Then create a new object called hc2021_inpat_migraine</span></span>
<span id="cb53-23"><a href="clnk.html#cb53-23" aria-hidden="true" tabindex="-1"></a><span class="do">### &amp; a new indicator variable called &quot;migraine_inpat = 1&quot;</span></span>
<span id="cb53-24"><a href="clnk.html#cb53-24" aria-hidden="true" tabindex="-1"></a><span class="do">### &amp; another new indicator variable called &quot;fyc = 1.&quot;</span></span>
<span id="cb53-25"><a href="clnk.html#cb53-25" aria-hidden="true" tabindex="-1"></a><span class="do">### Note: These are not unique rows (repeated dupersid)</span></span>
<span id="cb53-26"><a href="clnk.html#cb53-26" aria-hidden="true" tabindex="-1"></a>hc2021_inpat_migraine <span class="ot">=</span> <span class="fu">full_join</span>(</span>
<span id="cb53-27"><a href="clnk.html#cb53-27" aria-hidden="true" tabindex="-1"></a>  inpat_migraine <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">migraine_inpat =</span> <span class="dv">1</span>),</span>
<span id="cb53-28"><a href="clnk.html#cb53-28" aria-hidden="true" tabindex="-1"></a>  hc2021x <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">fyc =</span> <span class="dv">1</span>)</span>
<span id="cb53-29"><a href="clnk.html#cb53-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-30"><a href="clnk.html#cb53-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-31"><a href="clnk.html#cb53-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-32"><a href="clnk.html#cb53-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to person-level</span></span>
<span id="cb53-33"><a href="clnk.html#cb53-33" aria-hidden="true" tabindex="-1"></a><span class="do">### We have to do the estimations for the person-level at this stage</span></span>
<span id="cb53-34"><a href="clnk.html#cb53-34" aria-hidden="true" tabindex="-1"></a><span class="do">### We will estimate the total and mean values of the migraine-related expenditures</span></span>
<span id="cb53-35"><a href="clnk.html#cb53-35" aria-hidden="true" tabindex="-1"></a><span class="do">### The &quot;migraine_inpat&quot; will be used to create an indicator for migraine-related expenditures</span></span>
<span id="cb53-36"><a href="clnk.html#cb53-36" aria-hidden="true" tabindex="-1"></a><span class="do">### Need to set NA -&gt; zero.</span></span>
<span id="cb53-37"><a href="clnk.html#cb53-37" aria-hidden="true" tabindex="-1"></a>per_migraine_inpat <span class="ot">=</span> hc2021_inpat_migraine <span class="sc">%&gt;%</span></span>
<span id="cb53-38"><a href="clnk.html#cb53-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dupersid, varstr, varpsu, perwt21f) <span class="sc">%&gt;%</span></span>
<span id="cb53-39"><a href="clnk.html#cb53-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb53-40"><a href="clnk.html#cb53-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">totnights_inpat                =</span> <span class="fu">sum</span>(numnighx),</span>
<span id="cb53-41"><a href="clnk.html#cb53-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp_inpat                   =</span> <span class="fu">sum</span>(ipxp21x),</span>
<span id="cb53-42"><a href="clnk.html#cb53-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgexp_iptexp                  =</span> <span class="fu">mean</span>(iptexp21),</span>
<span id="cb53-43"><a href="clnk.html#cb53-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">totvisit_inpat                 =</span> <span class="fu">sum</span>(migraine_inpat_stays),</span>
<span id="cb53-44"><a href="clnk.html#cb53-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgvisit_inpat                 =</span> <span class="fu">mean</span>(migraine_inpat_stays),</span>
<span id="cb53-45"><a href="clnk.html#cb53-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">avgvisit_migraine_visits_inpat =</span> <span class="fu">mean</span>(migraine_inpat),</span>
<span id="cb53-46"><a href="clnk.html#cb53-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">migraine_inpat                 =</span> <span class="fu">max</span>(migraine_inpat)) <span class="sc">%&gt;%</span></span>
<span id="cb53-47"><a href="clnk.html#cb53-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(</span>
<span id="cb53-48"><a href="clnk.html#cb53-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">totnights_inpat =</span> <span class="dv">0</span>, <span class="at">totexp_inpat =</span> <span class="dv">0</span>, <span class="at">totvisit_inpat =</span> <span class="dv">0</span>, <span class="at">avgvisit_inpat =</span> <span class="dv">0</span>, <span class="at">avgvisit_migraine_visits_inpat =</span> <span class="dv">0</span>, <span class="at">migraine_inpat =</span> <span class="dv">0</span>)</span>
<span id="cb53-49"><a href="clnk.html#cb53-49" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-50"><a href="clnk.html#cb53-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-51"><a href="clnk.html#cb53-51" aria-hidden="true" tabindex="-1"></a><span class="do">### QC: Should have the same number as the full-year consolidated file</span></span>
<span id="cb53-52"><a href="clnk.html#cb53-52" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(per_migraine_inpat) <span class="sc">==</span> <span class="fu">nrow</span>(hc2021)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="part-4---combine-office-based-and-inpatient-expenditure-files" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Part 4 - Combine office-based and inpatient expenditure files<a href="clnk.html#part-4---combine-office-based-and-inpatient-expenditure-files" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once you have the <u>migraine-specific</u> inpatient expenditures dataframe completed, you can start the process to combine this with the <u>migraine-specific</u> office-based expenditures dataframe.</p>
<p>First, we want to merge using the <code>left_join</code> function the migraine-specific office-based expenditure dataframe with the Full-Year Consolidated file <code>hc2021x</code>. We do this because there were a couple of variables in <code>hc2021x</code> that we would like to keep such as the sex (<code>sex</code>) and race (<code>racev1x</code>) variables. We will call this new dataframe <code>combined_data_ob_part</code>.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="clnk.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># COMBINE OBVISIT AND INPAT - SPECIFIC EXPENDITURE FILES</span></span>
<span id="cb55-2"><a href="clnk.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Part 1: Combine the office-based visit exp file with the hc2021x file</span></span>
<span id="cb55-3"><a href="clnk.html#cb55-3" aria-hidden="true" tabindex="-1"></a>combined_data_ob_part <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb55-4"><a href="clnk.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  hc2021x, </span>
<span id="cb55-5"><a href="clnk.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  per_migraine_ob,</span>
<span id="cb55-6"><a href="clnk.html#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>, <span class="st">&quot;varstr&quot;</span>, <span class="st">&quot;varpsu&quot;</span>, <span class="st">&quot;perwt21f&quot;</span>)</span>
<span id="cb55-7"><a href="clnk.html#cb55-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Then, we want to merge the migraine-specific inpatient expenditures <code>per_migraine_inpat</code> to the dataframe <code>combined_data_ob_part</code> to create a new dataframe called <code>combined_data_ob_inpat_part</code>.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="clnk.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Part 2: Combine the inpatient stays file with the &quot;combined_data_ob_part&quot; file</span></span>
<span id="cb56-2"><a href="clnk.html#cb56-2" aria-hidden="true" tabindex="-1"></a>combined_data_ob_inpat_part <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb56-3"><a href="clnk.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  combined_data_ob_part, </span>
<span id="cb56-4"><a href="clnk.html#cb56-4" aria-hidden="true" tabindex="-1"></a>  per_migraine_inpat,</span>
<span id="cb56-5"><a href="clnk.html#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>, <span class="st">&quot;varstr&quot;</span>, <span class="st">&quot;varpsu&quot;</span>, <span class="st">&quot;perwt21f&quot;</span>)</span>
<span id="cb56-6"><a href="clnk.html#cb56-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Once that part is completed, we will have a dataframe that includes both the <u>migraine-specific</u> office-based visit and inpatient stay expenditures.</p>
<p>Next, we will take this opportunity to create an indicator variable for individuals with a migraine diagnosis or condition. So far, we have identified and isolated office-based and inpatient expenditures that were <u>migraine-specific</u>. This means that some individuals with a migraine diagnosis may not have accrued any <u>migraine-specific</u> office-based or inpatient expenditures. It’s possible that they have other expenditures, but those may not be <u>migraine-specific</u>. Hence, it is important that we create an indicator variable for those individuals with migraine in the comprehensive dataframe.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="clnk.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Part 3: Merge an indicator variable for migraine diagnosis. </span></span>
<span id="cb57-2"><a href="clnk.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Not all patients with migraine has an expenditure.</span></span>
<span id="cb57-3"><a href="clnk.html#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="clnk.html#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="do">### a) Create a dataframe with the dupersid and migraine indicator.</span></span>
<span id="cb57-5"><a href="clnk.html#cb57-5" aria-hidden="true" tabindex="-1"></a>migraine_distinct_qc <span class="ot">=</span> migraine <span class="sc">%&gt;%</span> </span>
<span id="cb57-6"><a href="clnk.html#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(dupersid) <span class="sc">%&gt;%</span></span>
<span id="cb57-7"><a href="clnk.html#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">migraine_indicator =</span> <span class="dv">1</span>)</span>
<span id="cb57-8"><a href="clnk.html#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="clnk.html#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="do">### b) Merge &quot;migraine_distinct_qc&quot; to the larger table.</span></span>
<span id="cb57-10"><a href="clnk.html#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="do">### This will be a 1 to 1 join.</span></span>
<span id="cb57-11"><a href="clnk.html#cb57-11" aria-hidden="true" tabindex="-1"></a>combined_data_migraine <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb57-12"><a href="clnk.html#cb57-12" aria-hidden="true" tabindex="-1"></a>  combined_data_ob_inpat_part,</span>
<span id="cb57-13"><a href="clnk.html#cb57-13" aria-hidden="true" tabindex="-1"></a>  migraine_distinct_qc,</span>
<span id="cb57-14"><a href="clnk.html#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>))</span>
<span id="cb57-15"><a href="clnk.html#cb57-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-16"><a href="clnk.html#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="do">### c) We also need to convert NA to 0 for the &quot;migraine_indicator&quot; variable.</span></span>
<span id="cb57-17"><a href="clnk.html#cb57-17" aria-hidden="true" tabindex="-1"></a>combined_data_migraine <span class="ot">=</span> combined_data_migraine <span class="sc">%&gt;%</span></span>
<span id="cb57-18"><a href="clnk.html#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(<span class="at">migraine_indicator =</span> <span class="dv">0</span>))</span></code></pre></div>
</div>
<div id="part-5---descriptive-analysis-using-survey-weights" class="section level3 hasAnchor" number="4.2.5">
<h3><span class="header-section-number">4.2.5</span> Part 5 - Descriptive analysis using survey weights<a href="clnk.html#part-5---descriptive-analysis-using-survey-weights" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are many ways to describe the expenditures in the migraine population.</p>
<p>First, we need to invoke the survey design for our data using the <code>svydesign</code> function. We will call this the <code>survey_cohort</code> design.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="clnk.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define person-level survey design</span></span>
<span id="cb58-2"><a href="clnk.html#cb58-2" aria-hidden="true" tabindex="-1"></a>survey_cohort <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb58-3"><a href="clnk.html#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="sc">~</span>varpsu, </span>
<span id="cb58-4"><a href="clnk.html#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span>varstr,</span>
<span id="cb58-5"><a href="clnk.html#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>perwt21f,</span>
<span id="cb58-6"><a href="clnk.html#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> combined_data_migraine,</span>
<span id="cb58-7"><a href="clnk.html#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">nest =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Next, we can provide the average costs and amounts of office-based visit and inpatient stay expenditures for the whole cohort, both individuals with and without a migraine condition. We will use the <code>svyby</code> function to group the findings into those with migraine <code>migraine_indicator == 1</code> and those without migraine <code>migraine_indicator == 0</code>.</p>
<p>Note: We expect to see zero costs and amount for the non-migraine individuals.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="clnk.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Average migraine-specific office-based visit costs and amount</span></span>
<span id="cb59-2"><a href="clnk.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totexp_ob, <span class="sc">~</span>migraine_indicator, survey_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator   totexp_ob          se
## 0                  0   0.0000000  0.00000000
## 1                  1 473.7215498 63.42344309</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="clnk.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totvisit_ob, <span class="sc">~</span>migraine_indicator, survey_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totvisit_ob           se
## 0                  0 0.000000000 0.0000000000
## 1                  1 1.874864152 0.2637829887</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="clnk.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Average migraine-specific inpatient costs and nights stayed</span></span>
<span id="cb63-2"><a href="clnk.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totexp_inpat, <span class="sc">~</span>migraine_indicator, survey_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totexp_inpat         se
## 0                  0   0.00000000  0.0000000
## 1                  1  69.78947691 37.9709726</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="clnk.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totnights_inpat, <span class="sc">~</span>migraine_indicator, survey_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totnights_inpat           se
## 0                  0   0.00000000000 0.0000000000
## 1                  1   0.02538119475 0.0133157815</code></pre>
<p>Based on these findings, the average cost for <u>migraine-specific</u> office-based visits was $474 for individuals with a migraine condition. The average number of office-based events was 1.9 events per individual with a migraine condition.</p>
<p>The average <u>migraine-specific</u> inpatient stay expenditure was $70 per individual with a migraine condition. The average <u>migraine-specific</u> inpatient nights was 0.025 nights per individual with a migraine condition.</p>
<p>Among individual without a migraine condition, the averages would have been zero.</p>
<p>Alternatively, we could have done this using a subset of the migraine cohort, but this will require us to create a subset of individuals with a migraine condition, which we will call <code>migraine_cohort</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="clnk.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subgroup of individuals with inpatient stays for migraines</span></span>
<span id="cb67-2"><a href="clnk.html#cb67-2" aria-hidden="true" tabindex="-1"></a>migraine_cohort <span class="ot">=</span> <span class="fu">subset</span>(survey_cohort, migraine_indicator <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Once we have the subset, we can provide the mean <u>migraine-specific</u> office-based and inpatient expenditures. Comparing the results from the subset to the whole cohort, we find that for individuals with the migraine indicator <code>migraine_indiciator == 1</code>, the average costs and amount of office-based and inpatient expenditures are the same.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="clnk.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Average migraine-specific office-based visit costs and amount</span></span>
<span id="cb68-2"><a href="clnk.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totexp_ob, <span class="sc">~</span>migraine_indicator, migraine_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator   totexp_ob          se
## 1                  1 473.7215498 63.42344309</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="clnk.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totvisit_ob, <span class="sc">~</span>migraine_indicator, migraine_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totvisit_ob           se
## 1                  1 1.874864152 0.2637829887</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="clnk.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Average migraine-specific inpatient costs and nights stayed</span></span>
<span id="cb72-2"><a href="clnk.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totexp_inpat, <span class="sc">~</span>migraine_indicator, migraine_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totexp_inpat         se
## 1                  1  69.78947691 37.9709726</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="clnk.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>totnights_inpat, <span class="sc">~</span>migraine_indicator, migraine_cohort, svymean)</span></code></pre></div>
<pre><code>##   migraine_indicator totnights_inpat           se
## 1                  1   0.02538119475 0.0133157815</code></pre>
<p>The average values for individuals with a migraine condition should be exactly the same in the subset and the whole cohort.</p>
<p>But what if we are interested in <u>migraine-specific</u> expenditures for only those individuals with a migraine AND non-zero expenditures? This would mean that we will have EXCLUDE individual with a migraine condition and ZERO expenditures.</p>
<p>We can do this with another subset.</p>
<p>The first subset we will do is the <u>migraine-specific</u> office-based visit. We will subset our migraine group from the <code>per_migraine_ob</code> dataframe and call it <code>migraine_ob_nonzero</code> to reflect the non-zero expenditures of the migraine only cohort. We’ll all this subset <code>migraineOB</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="clnk.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define person-level survey design</span></span>
<span id="cb76-2"><a href="clnk.html#cb76-2" aria-hidden="true" tabindex="-1"></a>migraine_ob_nonzero <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb76-3"><a href="clnk.html#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="sc">~</span>varpsu, </span>
<span id="cb76-4"><a href="clnk.html#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span>varstr,</span>
<span id="cb76-5"><a href="clnk.html#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>perwt21f,</span>
<span id="cb76-6"><a href="clnk.html#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> per_migraine_ob,</span>
<span id="cb76-7"><a href="clnk.html#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">nest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-8"><a href="clnk.html#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="clnk.html#cb76-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Subgroup of individuals with office-based for migraines</span></span>
<span id="cb76-10"><a href="clnk.html#cb76-10" aria-hidden="true" tabindex="-1"></a>migraineOB <span class="ot">=</span> <span class="fu">subset</span>(migraine_ob_nonzero, migraine_ob <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Once we have the new subset, we can estimate the average expenditures for <u>migraine-specific</u> office-based visits.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="clnk.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>totexp_ob, <span class="at">design =</span> migraineOB) <span class="co"># Mean office-based expenditures</span></span></code></pre></div>
<pre><code>##                mean        SE
## totexp_ob 988.27575 126.33587</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="clnk.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>totvisit_ob, <span class="at">design =</span> migraineOB) <span class="co"># Mean migraine office-based visits</span></span></code></pre></div>
<pre><code>##                  mean     SE
## totvisit_ob 3.9113331 0.5329</code></pre>
<p>Based on these findings, among individuals with a migraine condition and non-zero migraine-specific expenditures, the average <u>migraine-specific</u> office-based costs was $988 and the average number of <u>migraine-specific</u> office-based events was 3.9 events. This is very different from the $474 and 1.9 office-based events previously reported for the migraine population.</p>
<p>We can also do this for the inpatient expenditures subset, which we will call <code>migraineINPAT</code>.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="clnk.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define person-level survey design</span></span>
<span id="cb81-2"><a href="clnk.html#cb81-2" aria-hidden="true" tabindex="-1"></a>migraine_inpat_nonzero <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb81-3"><a href="clnk.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="sc">~</span>varpsu, </span>
<span id="cb81-4"><a href="clnk.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">strata =</span> <span class="sc">~</span>varstr,</span>
<span id="cb81-5"><a href="clnk.html#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>perwt21f,</span>
<span id="cb81-6"><a href="clnk.html#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> per_migraine_inpat,</span>
<span id="cb81-7"><a href="clnk.html#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">nest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb81-8"><a href="clnk.html#cb81-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb81-9"><a href="clnk.html#cb81-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Subgroup of individuals with office-based for migraines</span></span>
<span id="cb81-10"><a href="clnk.html#cb81-10" aria-hidden="true" tabindex="-1"></a>migraineINPAT <span class="ot">=</span> <span class="fu">subset</span>(migraine_inpat_nonzero, migraine_inpat <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb81-11"><a href="clnk.html#cb81-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-12"><a href="clnk.html#cb81-12" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>totexp_inpat, <span class="at">design =</span> migraineINPAT) <span class="co"># Mean inpatient stays expenditures</span></span></code></pre></div>
<pre><code>##                   mean        SE
## totexp_inpat 7364.0586 1138.0975</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="clnk.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>totnights_inpat, <span class="at">design =</span> migraineINPAT) <span class="co"># Mean inpatient stays nights </span></span></code></pre></div>
<pre><code>##                      mean      SE
## totnights_inpat 2.6781775 0.65583</code></pre>
<p>Based on these findings, among individuals with a migraine condition and non-zero migraine-specific expenditures, the average <u>migraine-specific</u> inpatient stay costs was $7364 and the average number of nights stayed was 2.7 nights. This is very different from the $70 and 0.025 nights previously reported for the migraine population.</p>
<p>Depending on how you define your cohort, these averages will be different.</p>
<p>There are 756 individuals with a migraine condition, but only 353 of those with a <u>migraine-specific</u> office-based visit expenditure and 7 of those with a <u>migraine-specific</u> inpatient stay expenditure.</p>
<p>A summary of the findings is provided below:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-61"></span>
<img src="Figure%204_4.png" alt="Summary of findings." width="100%" />
<p class="caption">
Figure 4.4: Summary of findings.
</p>
</div>
</div>
</div>
<div id="conclusions-3" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Conclusions<a href="clnk.html#conclusions-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can link events with specific conditions to get a more precise estimate of the expenditures. In this motivating example, we linked the migraine condition to its events and estimated the average office-based visit and inpatient stay expenditures. But we also explored the differences in these average when the denominator is restricted further to those with non-zero condition-specific expenditures. This process can be generalized to other conditions and other types of events.</p>
</div>
<div id="acknowledgements-3" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Acknowledgements<a href="clnk.html#acknowledgements-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This tutorial would not be possible with the resources provided by <a href="https://github.com/HHS-AHRQ/MEPS">AHRQ MEPS GitHub site</a>. The resources are amazing, and the codes are available for Stata, R, and SAS. Each exercise provide a new perspective on how to leverage the MEPS dataset for anyone’s research or investigations. I highly encourage people to visit their site.</p>
</div>
<div id="work-in-progress" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Work in progress<a href="clnk.html#work-in-progress" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is a work in progress so expect some updates in the future.</p>
</div>
<div id="disclaimers" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Disclaimers<a href="clnk.html#disclaimers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Any errors or mistakes are those of the author.</p>
<p>This is only for educational purposes.</p>
<p>This was built under R version 4.2.2 “Innocent and Trusting”</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="weights.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="trends.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-clnk.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
