<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Interrupted time series analysis (ITSA) with R: A short tutorial | MEPS tutorials</title>
  <meta name="description" content="This is a collection of MEPS tutorials." />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Interrupted time series analysis (ITSA) with R: A short tutorial | MEPS tutorials" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a collection of MEPS tutorials." />
  <meta name="github-repo" content="mbounthavong/MEPS_tutorials_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Interrupted time series analysis (ITSA) with R: A short tutorial | MEPS tutorials" />
  
  <meta name="twitter:description" content="This is a collection of MEPS tutorials." />
  

<meta name="author" content="Mark Bounthavong" />


<meta name="date" content="2024-01-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="trends.html"/>
<link rel="next" href="notes.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MEPS Tutorials Collection</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#book-link"><i class="fa fa-check"></i>Book link</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#table-of-contents"><i class="fa fa-check"></i>Table of contents</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Loading MEPS data into R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#meps-data"><i class="fa fa-check"></i><b>1.2</b> MEPS Data</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#load-meps-data-into-r"><i class="fa fa-check"></i><b>1.3</b> Load MEPS data into R</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#conclusions"><i class="fa fa-check"></i><b>1.4</b> Conclusions</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#acknowledgements"><i class="fa fa-check"></i><b>1.5</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="merging.html"><a href="merging.html"><i class="fa fa-check"></i><b>2</b> Merging files</a>
<ul>
<li class="chapter" data-level="2.1" data-path="merging.html"><a href="merging.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="merging.html"><a href="merging.html#load-meps-data"><i class="fa fa-check"></i><b>2.2</b> Load MEPS data</a></li>
<li class="chapter" data-level="2.3" data-path="merging.html"><a href="merging.html#merge-meps-data"><i class="fa fa-check"></i><b>2.3</b> Merge MEPS data</a></li>
<li class="chapter" data-level="2.4" data-path="merging.html"><a href="merging.html#reduce-dataframe-to-a-few-variables"><i class="fa fa-check"></i><b>2.4</b> Reduce dataframe to a few variables</a></li>
<li class="chapter" data-level="2.5" data-path="merging.html"><a href="merging.html#add-an-indicator-for-a-specific-icd10-diagnostic-code"><i class="fa fa-check"></i><b>2.5</b> Add an indicator for a specific ICD10 diagnostic code</a></li>
<li class="chapter" data-level="2.6" data-path="merging.html"><a href="merging.html#collapse-dataframe-to-a-single-unique-patient"><i class="fa fa-check"></i><b>2.6</b> Collapse dataframe to a single unique patient</a></li>
<li class="chapter" data-level="2.7" data-path="merging.html"><a href="merging.html#conclusions-1"><i class="fa fa-check"></i><b>2.7</b> Conclusions</a></li>
<li class="chapter" data-level="2.8" data-path="merging.html"><a href="merging.html#acknowledgements-1"><i class="fa fa-check"></i><b>2.8</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="weights.html"><a href="weights.html"><i class="fa fa-check"></i><b>3</b> Applying weights</a>
<ul>
<li class="chapter" data-level="3.1" data-path="weights.html"><a href="weights.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="weights.html"><a href="weights.html#types-of-weights"><i class="fa fa-check"></i><b>3.2</b> Types of weights</a></li>
<li class="chapter" data-level="3.3" data-path="weights.html"><a href="weights.html#loading-the-data"><i class="fa fa-check"></i><b>3.3</b> Loading the data</a></li>
<li class="chapter" data-level="3.4" data-path="weights.html"><a href="weights.html#perform-descriptive-analysis"><i class="fa fa-check"></i><b>3.4</b> Perform descriptive analysis</a></li>
<li class="chapter" data-level="3.5" data-path="weights.html"><a href="weights.html#conclusions-2"><i class="fa fa-check"></i><b>3.5</b> Conclusions</a></li>
<li class="chapter" data-level="3.6" data-path="weights.html"><a href="weights.html#acknowledgements-2"><i class="fa fa-check"></i><b>3.6</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="clnk.html"><a href="clnk.html"><i class="fa fa-check"></i><b>4</b> Using condition-event link (<code>CLNK</code>) file</a>
<ul>
<li class="chapter" data-level="4.1" data-path="clnk.html"><a href="clnk.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="clnk.html"><a href="clnk.html#motivating-example---migraine-specific-expenditures"><i class="fa fa-check"></i><b>4.2</b> Motivating example - Migraine-specific expenditures</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="clnk.html"><a href="clnk.html#part-1---setup"><i class="fa fa-check"></i><b>4.2.1</b> Part 1 - Setup</a></li>
<li class="chapter" data-level="4.2.2" data-path="clnk.html"><a href="clnk.html#part-2---migraine-specific-office-based-expenditures"><i class="fa fa-check"></i><b>4.2.2</b> Part 2 - Migraine-specific office-based expenditures</a></li>
<li class="chapter" data-level="4.2.3" data-path="clnk.html"><a href="clnk.html#part-3---migraine-specific-inpatient-expenditures"><i class="fa fa-check"></i><b>4.2.3</b> Part 3 - Migraine-specific inpatient expenditures</a></li>
<li class="chapter" data-level="4.2.4" data-path="clnk.html"><a href="clnk.html#part-4---combine-office-based-and-inpatient-expenditure-files"><i class="fa fa-check"></i><b>4.2.4</b> Part 4 - Combine office-based and inpatient expenditure files</a></li>
<li class="chapter" data-level="4.2.5" data-path="clnk.html"><a href="clnk.html#part-5---descriptive-analysis-using-survey-weights"><i class="fa fa-check"></i><b>4.2.5</b> Part 5 - Descriptive analysis using survey weights</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="clnk.html"><a href="clnk.html#conclusions-3"><i class="fa fa-check"></i><b>4.3</b> Conclusions</a></li>
<li class="chapter" data-level="4.4" data-path="clnk.html"><a href="clnk.html#acknowledgements-3"><i class="fa fa-check"></i><b>4.4</b> Acknowledgements</a></li>
<li class="chapter" data-level="4.5" data-path="clnk.html"><a href="clnk.html#work-in-progress"><i class="fa fa-check"></i><b>4.5</b> Work in progress</a></li>
<li class="chapter" data-level="4.6" data-path="clnk.html"><a href="clnk.html#disclaimers"><i class="fa fa-check"></i><b>4.6</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="trends.html"><a href="trends.html"><i class="fa fa-check"></i><b>5</b> Simple trend analysis with linear models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="trends.html"><a href="trends.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="trends.html"><a href="trends.html#motivating-example"><i class="fa fa-check"></i><b>5.2</b> Motivating example</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="trends.html"><a href="trends.html#loading-the-libraries"><i class="fa fa-check"></i><b>5.2.1</b> Loading the libraries</a></li>
<li class="chapter" data-level="5.2.2" data-path="trends.html"><a href="trends.html#loading-data-into-the-r-environment"><i class="fa fa-check"></i><b>5.2.2</b> Loading data into the R environment</a></li>
<li class="chapter" data-level="5.2.3" data-path="trends.html"><a href="trends.html#download-the-linkage-file"><i class="fa fa-check"></i><b>5.2.3</b> Download the linkage file</a></li>
<li class="chapter" data-level="5.2.4" data-path="trends.html"><a href="trends.html#creating-the-pooled-data-file"><i class="fa fa-check"></i><b>5.2.4</b> Creating the pooled data file</a></li>
<li class="chapter" data-level="5.2.5" data-path="trends.html"><a href="trends.html#merging-with-pooled-survey-primary-sampling-strata-and-unit"><i class="fa fa-check"></i><b>5.2.5</b> Merging with pooled survey primary sampling strata and unit</a></li>
<li class="chapter" data-level="5.2.6" data-path="trends.html"><a href="trends.html#create-factor-variables"><i class="fa fa-check"></i><b>5.2.6</b> Create factor variables</a></li>
<li class="chapter" data-level="5.2.7" data-path="trends.html"><a href="trends.html#set-the-survey-options"><i class="fa fa-check"></i><b>5.2.7</b> Set the survey options</a></li>
<li class="chapter" data-level="5.2.8" data-path="trends.html"><a href="trends.html#trend-analysis---plot-the-total-healthcare-costs-by-sex-across-time"><i class="fa fa-check"></i><b>5.2.8</b> Trend analysis - Plot the total healthcare costs by sex across time</a></li>
<li class="chapter" data-level="5.2.9" data-path="trends.html"><a href="trends.html#regression-model"><i class="fa fa-check"></i><b>5.2.9</b> Regression model</a></li>
<li class="chapter" data-level="5.2.10" data-path="trends.html"><a href="trends.html#average-marginal-effects-between-males-and-females-at-each-year"><i class="fa fa-check"></i><b>5.2.10</b> Average marginal effects between males and females at each year</a></li>
<li class="chapter" data-level="5.2.11" data-path="trends.html"><a href="trends.html#average-marginal-effects-between-years-for-males-and-females"><i class="fa fa-check"></i><b>5.2.11</b> Average marginal effects between years for males and females</a></li>
<li class="chapter" data-level="5.2.12" data-path="trends.html"><a href="trends.html#plot-the-average-marginal-effects"><i class="fa fa-check"></i><b>5.2.12</b> Plot the average marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="trends.html"><a href="trends.html#conclusions-4"><i class="fa fa-check"></i><b>5.3</b> Conclusions</a></li>
<li class="chapter" data-level="5.4" data-path="trends.html"><a href="trends.html#acknowledgements-4"><i class="fa fa-check"></i><b>5.4</b> Acknowledgements</a></li>
<li class="chapter" data-level="5.5" data-path="trends.html"><a href="trends.html#work-in-progress-1"><i class="fa fa-check"></i><b>5.5</b> Work in progress</a></li>
<li class="chapter" data-level="5.6" data-path="trends.html"><a href="trends.html#disclaimers-1"><i class="fa fa-check"></i><b>5.6</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="itsa.html"><a href="itsa.html"><i class="fa fa-check"></i><b>6</b> Interrupted time series analysis (ITSA) with R: A short tutorial</a>
<ul>
<li class="chapter" data-level="6.1" data-path="itsa.html"><a href="itsa.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="itsa.html"><a href="itsa.html#motivating-example---total-healthcare-costs-from-2016-to-2021-by-sex"><i class="fa fa-check"></i><b>6.2</b> Motivating example - Total Healthcare Costs from 2016 to 2021 by sex</a></li>
<li class="chapter" data-level="6.3" data-path="itsa.html"><a href="itsa.html#interrupted-time-series-analysis-design"><i class="fa fa-check"></i><b>6.3</b> Interrupted Time Series Analysis Design</a></li>
<li class="chapter" data-level="6.4" data-path="itsa.html"><a href="itsa.html#set-up-the-survey-options"><i class="fa fa-check"></i><b>6.4</b> Set up the survey options</a></li>
<li class="chapter" data-level="6.5" data-path="itsa.html"><a href="itsa.html#descriptive-analysis"><i class="fa fa-check"></i><b>6.5</b> Descriptive analysis</a></li>
<li class="chapter" data-level="6.6" data-path="itsa.html"><a href="itsa.html#linear-regression-model"><i class="fa fa-check"></i><b>6.6</b> Linear regression model</a></li>
<li class="chapter" data-level="6.7" data-path="itsa.html"><a href="itsa.html#plot"><i class="fa fa-check"></i><b>6.7</b> Plot</a></li>
<li class="chapter" data-level="6.8" data-path="itsa.html"><a href="itsa.html#parallel-trends-assumption"><i class="fa fa-check"></i><b>6.8</b> Parallel trends assumption</a></li>
<li class="chapter" data-level="6.9" data-path="itsa.html"><a href="itsa.html#additional-estimations"><i class="fa fa-check"></i><b>6.9</b> Additional estimations</a></li>
<li class="chapter" data-level="6.10" data-path="itsa.html"><a href="itsa.html#issues-with-the-current-model"><i class="fa fa-check"></i><b>6.10</b> Issues with the current model</a></li>
<li class="chapter" data-level="6.11" data-path="itsa.html"><a href="itsa.html#workaround-using-a-linear-spline-model"><i class="fa fa-check"></i><b>6.11</b> Workaround using a linear spline model</a></li>
<li class="chapter" data-level="6.12" data-path="itsa.html"><a href="itsa.html#differences-in-level-immediately-after-implementation-of-the-intervention"><i class="fa fa-check"></i><b>6.12</b> Differences in level immediately after implementation of the intervention</a></li>
<li class="chapter" data-level="6.13" data-path="itsa.html"><a href="itsa.html#difference-in-differences-estimation"><i class="fa fa-check"></i><b>6.13</b> Difference-in-differences estimation</a></li>
<li class="chapter" data-level="6.14" data-path="itsa.html"><a href="itsa.html#putting-it-all-together"><i class="fa fa-check"></i><b>6.14</b> Putting it all together</a></li>
<li class="chapter" data-level="6.15" data-path="itsa.html"><a href="itsa.html#conclusions-5"><i class="fa fa-check"></i><b>6.15</b> Conclusions</a></li>
<li class="chapter" data-level="6.16" data-path="itsa.html"><a href="itsa.html#acknowledgements-5"><i class="fa fa-check"></i><b>6.16</b> Acknowledgements</a></li>
<li class="chapter" data-level="6.17" data-path="itsa.html"><a href="itsa.html#work-in-progress-2"><i class="fa fa-check"></i><b>6.17</b> Work in progress</a></li>
<li class="chapter" data-level="6.18" data-path="itsa.html"><a href="itsa.html#disclaimers-2"><i class="fa fa-check"></i><b>6.18</b> Disclaimers</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="notes.html"><a href="notes.html"><i class="fa fa-check"></i><b>7</b> Helpful Notes</a>
<ul>
<li class="chapter" data-level="7.1" data-path="notes.html"><a href="notes.html#introduction-6"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="notes.html"><a href="notes.html#meps-file-names"><i class="fa fa-check"></i><b>7.1.1</b> 1. MEPS file names</a></li>
<li class="chapter" data-level="7.1.2" data-path="notes.html"><a href="notes.html#expenditure-categories"><i class="fa fa-check"></i><b>7.1.2</b> 2. Expenditure categories</a></li>
<li class="chapter" data-level="7.1.3" data-path="notes.html"><a href="notes.html#sources-of-payments"><i class="fa fa-check"></i><b>7.1.3</b> 3. Sources of payments</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="notes.html"><a href="notes.html#references"><i class="fa fa-check"></i><b>7.2</b> References</a></li>
<li class="chapter" data-level="7.3" data-path="notes.html"><a href="notes.html#disclaimer"><i class="fa fa-check"></i><b>7.3</b> Disclaimer</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MEPS tutorials</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="itsa" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Interrupted time series analysis (ITSA) with R: A short tutorial<a href="itsa.html#itsa" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-5" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Introduction<a href="itsa.html#introduction-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Previously, I wrote a tutorial on how to perform an interrupted time series analysis (ITSA) in <code>Stata</code>, which is located on my RPubs site (<a href="https://rpubs.com/mbounthavong/itsa_stata">link</a>). This had me thinking of how to perform an ITSA using <code>R</code>. So, I decided to create a short tutorial on how to perform an ITSA on <code>R</code> using the <a href="https://meps.ahrq.gov/mepsweb/">Agency for Healthcare Research and Quality (AHRQ) Medical Expenditure Panel Survey (MEPS)</a> dataset. I tried several ways to do this, and I think I’ve found a nice approach that leverages survey weights from the MEPS database. Although I’m writing this ITSA tutorial with this approach, I plan on researching <u>other methods</u> to perform an ITSA in <code>R</code> so stay tuned.</p>
<p>This short tutorial will summarize how to perform an ITSA using a linear regression model with survey weights applied from the MEPS database. (Note: I previously wrote a tutorial on how to apply weights from MEPS data (<a href="https://rpubs.com/mbounthavong/MEPS_tutorial_3_applying_weights">link</a>).</p>
</div>
<div id="motivating-example---total-healthcare-costs-from-2016-to-2021-by-sex" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Motivating example - Total Healthcare Costs from 2016 to 2021 by sex<a href="itsa.html#motivating-example---total-healthcare-costs-from-2016-to-2021-by-sex" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll use the MEPS database to compare the trends in total healthcare costs between sex. We’ll assume that a policy or intervention was implemented in 2019, which may have changed the healthcare costs levels and trends between males and females.</p>
<p>I pooled data from 2016 to 2021 and adjusted the weights. I won’t go into details on how to create this dataset for this tutorial since I provided a detailed summary in a previous tutorial. For more details on how I created this dataset, please refer to my previous tutorial (<a href="https://rpubs.com/mbounthavong/MEPS_tutorial_5_simple_trend_analysis">link</a>).</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="itsa.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To install MEPS package in R, you need to do a couple of things.</span></span>
<span id="cb113-2"><a href="itsa.html#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 1: Install the &quot;devtools&quot; package. </span></span>
<span id="cb113-3"><a href="itsa.html#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;devtools&quot;)</span></span>
<span id="cb113-4"><a href="itsa.html#cb113-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-5"><a href="itsa.html#cb113-5" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 2: Install the &quot;MEPS&quot; package from the AHRQ MEPS GitHub site. </span></span>
<span id="cb113-6"><a href="itsa.html#cb113-6" aria-hidden="true" tabindex="-1"></a><span class="co">#devtools::install_github(&quot;e-mitchell/meps_r_pkg/MEPS&quot;)</span></span>
<span id="cb113-7"><a href="itsa.html#cb113-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-8"><a href="itsa.html#cb113-8" aria-hidden="true" tabindex="-1"></a><span class="do">### step 3: Load the MEPS package</span></span>
<span id="cb113-9"><a href="itsa.html#cb113-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;MEPS&quot;</span>) <span class="do">## You need to load the library every time you restart R</span></span>
<span id="cb113-10"><a href="itsa.html#cb113-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-11"><a href="itsa.html#cb113-11" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 4: Load the other libraries</span></span>
<span id="cb113-12"><a href="itsa.html#cb113-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;survey&quot;</span>)</span>
<span id="cb113-13"><a href="itsa.html#cb113-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;foreign&quot;</span>)</span>
<span id="cb113-14"><a href="itsa.html#cb113-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb113-15"><a href="itsa.html#cb113-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb113-16"><a href="itsa.html#cb113-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;questionr&quot;</span>) <span class="co"># remotes::install_github(&quot;juba/questionr&quot;)</span></span>
<span id="cb113-17"><a href="itsa.html#cb113-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;lspline&quot;</span>)  <span class="co"># devtools::install_github(&quot;mbojan/lspline&quot;, build_vignettes=TRUE)</span></span>
<span id="cb113-18"><a href="itsa.html#cb113-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggeffects&quot;</span>) <span class="co"># remotes::install_github(&quot;strengejacke/ggeffects&quot;)</span></span>
<span id="cb113-19"><a href="itsa.html#cb113-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;margins&quot;</span>)</span>
<span id="cb113-20"><a href="itsa.html#cb113-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-21"><a href="itsa.html#cb113-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-22"><a href="itsa.html#cb113-22" aria-hidden="true" tabindex="-1"></a><span class="co"># There are two ways to load data from AHRQ MEPS website:</span></span>
<span id="cb113-23"><a href="itsa.html#cb113-23" aria-hidden="true" tabindex="-1"></a><span class="do">#### Method 1: Load data from AHRQ MEPS website</span></span>
<span id="cb113-24"><a href="itsa.html#cb113-24" aria-hidden="true" tabindex="-1"></a>hc2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h233&quot;</span>)</span>
<span id="cb113-25"><a href="itsa.html#cb113-25" aria-hidden="true" tabindex="-1"></a>hc2020 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h224&quot;</span>)</span>
<span id="cb113-26"><a href="itsa.html#cb113-26" aria-hidden="true" tabindex="-1"></a>hc2019 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h216&quot;</span>)</span>
<span id="cb113-27"><a href="itsa.html#cb113-27" aria-hidden="true" tabindex="-1"></a>hc2018 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h209&quot;</span>)</span>
<span id="cb113-28"><a href="itsa.html#cb113-28" aria-hidden="true" tabindex="-1"></a>hc2017 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h201&quot;</span>)</span>
<span id="cb113-29"><a href="itsa.html#cb113-29" aria-hidden="true" tabindex="-1"></a>hc2016 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">file =</span> <span class="st">&quot;h192&quot;</span>)</span>
<span id="cb113-30"><a href="itsa.html#cb113-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-31"><a href="itsa.html#cb113-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-32"><a href="itsa.html#cb113-32" aria-hidden="true" tabindex="-1"></a><span class="do">#### Method 2: Load data from AHRQ MEPS website</span></span>
<span id="cb113-33"><a href="itsa.html#cb113-33" aria-hidden="true" tabindex="-1"></a>hc2021 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2021</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-34"><a href="itsa.html#cb113-34" aria-hidden="true" tabindex="-1"></a>hc2020 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2020</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-35"><a href="itsa.html#cb113-35" aria-hidden="true" tabindex="-1"></a>hc2019 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2019</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-36"><a href="itsa.html#cb113-36" aria-hidden="true" tabindex="-1"></a>hc2018 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2018</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-37"><a href="itsa.html#cb113-37" aria-hidden="true" tabindex="-1"></a>hc2017 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2017</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-38"><a href="itsa.html#cb113-38" aria-hidden="true" tabindex="-1"></a>hc2016 <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">year =</span> <span class="dv">2016</span>, <span class="at">type =</span> <span class="st">&quot;FYC&quot;</span>)</span>
<span id="cb113-39"><a href="itsa.html#cb113-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-40"><a href="itsa.html#cb113-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-41"><a href="itsa.html#cb113-41" aria-hidden="true" tabindex="-1"></a><span class="do">## Change column names to lowercase</span></span>
<span id="cb113-42"><a href="itsa.html#cb113-42" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2021) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2021))</span>
<span id="cb113-43"><a href="itsa.html#cb113-43" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2020) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2020))</span>
<span id="cb113-44"><a href="itsa.html#cb113-44" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2019) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2019))</span>
<span id="cb113-45"><a href="itsa.html#cb113-45" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2018) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2018))</span>
<span id="cb113-46"><a href="itsa.html#cb113-46" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2017) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2017))</span>
<span id="cb113-47"><a href="itsa.html#cb113-47" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(hc2016) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(hc2016))</span>
<span id="cb113-48"><a href="itsa.html#cb113-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-49"><a href="itsa.html#cb113-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-50"><a href="itsa.html#cb113-50" aria-hidden="true" tabindex="-1"></a><span class="co"># We need the linkage file with the appropriate stratum of the primary sampling unit (STRA9621) and primary sampling unit (PSU9621). (Note: Each year, the linkage file sampling unit name changes)</span></span>
<span id="cb113-51"><a href="itsa.html#cb113-51" aria-hidden="true" tabindex="-1"></a>linkage <span class="ot">=</span> <span class="fu">read_MEPS</span>(<span class="at">type =</span> <span class="st">&quot;Pooled linkage&quot;</span>) </span>
<span id="cb113-52"><a href="itsa.html#cb113-52" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(linkage) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(linkage)) <span class="co"># change variable name to lower case</span></span>
<span id="cb113-53"><a href="itsa.html#cb113-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-54"><a href="itsa.html#cb113-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-55"><a href="itsa.html#cb113-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-56"><a href="itsa.html#cb113-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Select specific variables</span></span>
<span id="cb113-57"><a href="itsa.html#cb113-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-58"><a href="itsa.html#cb113-58" aria-hidden="true" tabindex="-1"></a><span class="do">### 2021</span></span>
<span id="cb113-59"><a href="itsa.html#cb113-59" aria-hidden="true" tabindex="-1"></a>hc2021p <span class="ot">=</span> hc2021 <span class="sc">%&gt;%</span></span>
<span id="cb113-60"><a href="itsa.html#cb113-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-61"><a href="itsa.html#cb113-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt21f,</span>
<span id="cb113-62"><a href="itsa.html#cb113-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp21,</span>
<span id="cb113-63"><a href="itsa.html#cb113-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp21) <span class="sc">%&gt;%</span></span>
<span id="cb113-64"><a href="itsa.html#cb113-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-65"><a href="itsa.html#cb113-65" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-66"><a href="itsa.html#cb113-66" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-67"><a href="itsa.html#cb113-67" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-68"><a href="itsa.html#cb113-68" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-69"><a href="itsa.html#cb113-69" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-70"><a href="itsa.html#cb113-70" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-71"><a href="itsa.html#cb113-71" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-72"><a href="itsa.html#cb113-72" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-73"><a href="itsa.html#cb113-73" aria-hidden="true" tabindex="-1"></a>hc2021p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2021</span></span>
<span id="cb113-74"><a href="itsa.html#cb113-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-75"><a href="itsa.html#cb113-75" aria-hidden="true" tabindex="-1"></a><span class="do">### 2020</span></span>
<span id="cb113-76"><a href="itsa.html#cb113-76" aria-hidden="true" tabindex="-1"></a>hc2020p <span class="ot">=</span> hc2020 <span class="sc">%&gt;%</span></span>
<span id="cb113-77"><a href="itsa.html#cb113-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-78"><a href="itsa.html#cb113-78" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt20f,</span>
<span id="cb113-79"><a href="itsa.html#cb113-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp20,</span>
<span id="cb113-80"><a href="itsa.html#cb113-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp20) <span class="sc">%&gt;%</span></span>
<span id="cb113-81"><a href="itsa.html#cb113-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-82"><a href="itsa.html#cb113-82" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-83"><a href="itsa.html#cb113-83" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-84"><a href="itsa.html#cb113-84" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-85"><a href="itsa.html#cb113-85" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-86"><a href="itsa.html#cb113-86" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-87"><a href="itsa.html#cb113-87" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-88"><a href="itsa.html#cb113-88" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-89"><a href="itsa.html#cb113-89" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-90"><a href="itsa.html#cb113-90" aria-hidden="true" tabindex="-1"></a>hc2020p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2020</span></span>
<span id="cb113-91"><a href="itsa.html#cb113-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-92"><a href="itsa.html#cb113-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-93"><a href="itsa.html#cb113-93" aria-hidden="true" tabindex="-1"></a><span class="do">### 2019</span></span>
<span id="cb113-94"><a href="itsa.html#cb113-94" aria-hidden="true" tabindex="-1"></a>hc2019p <span class="ot">=</span> hc2019 <span class="sc">%&gt;%</span></span>
<span id="cb113-95"><a href="itsa.html#cb113-95" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-96"><a href="itsa.html#cb113-96" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt19f,</span>
<span id="cb113-97"><a href="itsa.html#cb113-97" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp19,</span>
<span id="cb113-98"><a href="itsa.html#cb113-98" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp19) <span class="sc">%&gt;%</span></span>
<span id="cb113-99"><a href="itsa.html#cb113-99" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-100"><a href="itsa.html#cb113-100" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-101"><a href="itsa.html#cb113-101" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-102"><a href="itsa.html#cb113-102" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-103"><a href="itsa.html#cb113-103" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-104"><a href="itsa.html#cb113-104" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-105"><a href="itsa.html#cb113-105" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-106"><a href="itsa.html#cb113-106" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-107"><a href="itsa.html#cb113-107" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-108"><a href="itsa.html#cb113-108" aria-hidden="true" tabindex="-1"></a>hc2019p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2019</span></span>
<span id="cb113-109"><a href="itsa.html#cb113-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-110"><a href="itsa.html#cb113-110" aria-hidden="true" tabindex="-1"></a><span class="do">### 2018</span></span>
<span id="cb113-111"><a href="itsa.html#cb113-111" aria-hidden="true" tabindex="-1"></a>hc2018p <span class="ot">=</span> hc2018 <span class="sc">%&gt;%</span></span>
<span id="cb113-112"><a href="itsa.html#cb113-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-113"><a href="itsa.html#cb113-113" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt18f,</span>
<span id="cb113-114"><a href="itsa.html#cb113-114" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp18,</span>
<span id="cb113-115"><a href="itsa.html#cb113-115" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp18) <span class="sc">%&gt;%</span></span>
<span id="cb113-116"><a href="itsa.html#cb113-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-117"><a href="itsa.html#cb113-117" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-118"><a href="itsa.html#cb113-118" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-119"><a href="itsa.html#cb113-119" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-120"><a href="itsa.html#cb113-120" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-121"><a href="itsa.html#cb113-121" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-122"><a href="itsa.html#cb113-122" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-123"><a href="itsa.html#cb113-123" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-124"><a href="itsa.html#cb113-124" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-125"><a href="itsa.html#cb113-125" aria-hidden="true" tabindex="-1"></a>hc2018p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2018</span></span>
<span id="cb113-126"><a href="itsa.html#cb113-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-127"><a href="itsa.html#cb113-127" aria-hidden="true" tabindex="-1"></a><span class="do">### 2017</span></span>
<span id="cb113-128"><a href="itsa.html#cb113-128" aria-hidden="true" tabindex="-1"></a>hc2017p <span class="ot">=</span> hc2017 <span class="sc">%&gt;%</span></span>
<span id="cb113-129"><a href="itsa.html#cb113-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-130"><a href="itsa.html#cb113-130" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt17f,</span>
<span id="cb113-131"><a href="itsa.html#cb113-131" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp17,</span>
<span id="cb113-132"><a href="itsa.html#cb113-132" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp17) <span class="sc">%&gt;%</span></span>
<span id="cb113-133"><a href="itsa.html#cb113-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-134"><a href="itsa.html#cb113-134" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-135"><a href="itsa.html#cb113-135" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-136"><a href="itsa.html#cb113-136" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-137"><a href="itsa.html#cb113-137" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-138"><a href="itsa.html#cb113-138" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-139"><a href="itsa.html#cb113-139" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-140"><a href="itsa.html#cb113-140" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-141"><a href="itsa.html#cb113-141" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-142"><a href="itsa.html#cb113-142" aria-hidden="true" tabindex="-1"></a>hc2017p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2017</span></span>
<span id="cb113-143"><a href="itsa.html#cb113-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-144"><a href="itsa.html#cb113-144" aria-hidden="true" tabindex="-1"></a><span class="do">### 2016</span></span>
<span id="cb113-145"><a href="itsa.html#cb113-145" aria-hidden="true" tabindex="-1"></a>hc2016p <span class="ot">=</span> hc2016 <span class="sc">%&gt;%</span></span>
<span id="cb113-146"><a href="itsa.html#cb113-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb113-147"><a href="itsa.html#cb113-147" aria-hidden="true" tabindex="-1"></a>    <span class="at">perwt =</span> perwt16f,</span>
<span id="cb113-148"><a href="itsa.html#cb113-148" aria-hidden="true" tabindex="-1"></a>    <span class="at">totexp =</span> totexp16,</span>
<span id="cb113-149"><a href="itsa.html#cb113-149" aria-hidden="true" tabindex="-1"></a>    <span class="at">ertexp =</span> ertexp16) <span class="sc">%&gt;%</span></span>
<span id="cb113-150"><a href="itsa.html#cb113-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb113-151"><a href="itsa.html#cb113-151" aria-hidden="true" tabindex="-1"></a>    dupersid, </span>
<span id="cb113-152"><a href="itsa.html#cb113-152" aria-hidden="true" tabindex="-1"></a>    panel, </span>
<span id="cb113-153"><a href="itsa.html#cb113-153" aria-hidden="true" tabindex="-1"></a>    varstr, </span>
<span id="cb113-154"><a href="itsa.html#cb113-154" aria-hidden="true" tabindex="-1"></a>    varpsu,</span>
<span id="cb113-155"><a href="itsa.html#cb113-155" aria-hidden="true" tabindex="-1"></a>    perwt,</span>
<span id="cb113-156"><a href="itsa.html#cb113-156" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb113-157"><a href="itsa.html#cb113-157" aria-hidden="true" tabindex="-1"></a>    totexp,</span>
<span id="cb113-158"><a href="itsa.html#cb113-158" aria-hidden="true" tabindex="-1"></a>    ertexp)</span>
<span id="cb113-159"><a href="itsa.html#cb113-159" aria-hidden="true" tabindex="-1"></a>hc2016p<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="dv">2016</span></span>
<span id="cb113-160"><a href="itsa.html#cb113-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-161"><a href="itsa.html#cb113-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-162"><a href="itsa.html#cb113-162" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge data and adjust the person weight by 6 years</span></span>
<span id="cb113-163"><a href="itsa.html#cb113-163" aria-hidden="true" tabindex="-1"></a>pool_data <span class="ot">=</span> <span class="fu">bind_rows</span>(hc2021p, </span>
<span id="cb113-164"><a href="itsa.html#cb113-164" aria-hidden="true" tabindex="-1"></a>                      hc2020p,</span>
<span id="cb113-165"><a href="itsa.html#cb113-165" aria-hidden="true" tabindex="-1"></a>                      hc2019p,</span>
<span id="cb113-166"><a href="itsa.html#cb113-166" aria-hidden="true" tabindex="-1"></a>                      hc2018p,</span>
<span id="cb113-167"><a href="itsa.html#cb113-167" aria-hidden="true" tabindex="-1"></a>                      hc2017p,</span>
<span id="cb113-168"><a href="itsa.html#cb113-168" aria-hidden="true" tabindex="-1"></a>                      hc2016p) <span class="sc">%&gt;%</span></span>
<span id="cb113-169"><a href="itsa.html#cb113-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">poolwt =</span> perwt <span class="sc">/</span> <span class="dv">6</span>)</span>
<span id="cb113-170"><a href="itsa.html#cb113-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-171"><a href="itsa.html#cb113-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-172"><a href="itsa.html#cb113-172" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new variable for the pre-post index year at 2019</span></span>
<span id="cb113-173"><a href="itsa.html#cb113-173" aria-hidden="true" tabindex="-1"></a>pool_data<span class="sc">$</span>period[pool_data<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2016</span> <span class="sc">&amp;</span> pool_data<span class="sc">$</span>year <span class="sc">&lt;</span> <span class="dv">2019</span>] <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb113-174"><a href="itsa.html#cb113-174" aria-hidden="true" tabindex="-1"></a>pool_data<span class="sc">$</span>period[pool_data<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> pool_data<span class="sc">$</span>year <span class="sc">&lt;</span> <span class="dv">2022</span>] <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb113-175"><a href="itsa.html#cb113-175" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pool_data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 11
##   dupersid   panel            varstr varpsu perwt sex          totexp ertexp
##   &lt;chr&gt;      &lt;dbl+lbl&gt;         &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
## 1 2320005101 23 [23 PANEL 23]   2079      1 6785. 2 [2 FEMALE]   4908      0
## 2 2320005102 23 [23 PANEL 23]   2079      1 6177. 1 [1 MALE]    21257      0
## 3 2320006101 23 [23 PANEL 23]   2028      1 1599. 2 [2 FEMALE]    827      0
## 4 2320006102 23 [23 PANEL 23]   2028      1 1649. 1 [1 MALE]        0      0
## 5 2320006103 23 [23 PANEL 23]   2028      1 2892. 1 [1 MALE]        0      0
## 6 2320012102 23 [23 PANEL 23]   2069      2 1273. 2 [2 FEMALE]   9813      0
##    year poolwt period
##   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  2021  1131.      1
## 2  2021  1029.      1
## 3  2021   267.      1
## 4  2021   275.      1
## 5  2021   482.      1
## 6  2021   212.      1</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="itsa.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduce the linkage file to only include dupersid, panel, stra9621, psu9621</span></span>
<span id="cb115-2"><a href="itsa.html#cb115-2" aria-hidden="true" tabindex="-1"></a>linkage_file <span class="ot">=</span> linkage <span class="sc">%&gt;%</span></span>
<span id="cb115-3"><a href="itsa.html#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dupersid, panel, stra9621, psu9621)</span>
<span id="cb115-4"><a href="itsa.html#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="itsa.html#cb115-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge link file with main data</span></span>
<span id="cb115-6"><a href="itsa.html#cb115-6" aria-hidden="true" tabindex="-1"></a>pool_data_linked <span class="ot">=</span> <span class="fu">left_join</span>(pool_data,</span>
<span id="cb115-7"><a href="itsa.html#cb115-7" aria-hidden="true" tabindex="-1"></a>                             linkage_file, </span>
<span id="cb115-8"><a href="itsa.html#cb115-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;dupersid&quot;</span>, <span class="st">&quot;panel&quot;</span>))</span></code></pre></div>
</div>
<div id="interrupted-time-series-analysis-design" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Interrupted Time Series Analysis Design<a href="itsa.html#interrupted-time-series-analysis-design" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this ITSA motivating example, we are going to compare the trends in healthcare total costs between males and females before and after the hypothetical policy intervention, which was implemented in 2019. The ITSA design is illustrated in the figure below.</p>
<p>For this example, the ITSA model is denoted by the following:</p>
<p><span class="math inline">\(Y_i = \beta_0 + \beta_1(T_i) + \beta_2(X_i) + \beta_3(T_i * X_i) + \beta_4(Sex_i) + \beta_5(Sex_i * T_i) + \beta_6(Sex_i * X_i) + \beta_7(Sex_i * T_i * X_i) + \epsilon_i\)</span>,</p>
<p>where <span class="math inline">\(Sex_i\)</span> is a new variable that denotes the groups (e.g., sexes), <span class="math inline">\(\beta_4\)</span> denotes the difference in the outcomes between the groups (e.g., sexes) at beginning of the study (<span class="math inline">\(T = 0\)</span>), <span class="math inline">\(\beta_5\)</span> denotes the difference in the slopes between the groups before the intervention, <span class="math inline">\(\beta_6\)</span> denotes the difference in the level changes between the groups immediately after implementation of the intervention <span class="math inline">\(X\)</span>, and <span class="math inline">\(\beta_7\)</span> denotes the difference in the slopes after and before the intervention between the groups (e.g., difference-in-differences).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-82"></span>
<img src="Figure%206_1.png" alt="ITSA for two groups (`sex`) before and after the intervention (`X`)." width="100%" />
<p class="caption">
Figure 6.1: ITSA for two groups (<code>sex</code>) before and after the intervention (<code>X</code>).
</p>
</div>
</div>
<div id="set-up-the-survey-options" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Set up the survey options<a href="itsa.html#set-up-the-survey-options" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to estimate the appropriate costs and standard errors, we will need to set up the survey options and survey design using the weights from MEPS. We will use the <code>svydesign</code> function to load the primary sampling unit, individual weights, and strata, which we will then assign to an object called <code>survey_design</code>. Please see the code below:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="itsa.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the survey options</span></span>
<span id="cb116-2"><a href="itsa.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">survey.lonely.psu =</span> <span class="st">&quot;adjust&quot;</span>)</span>
<span id="cb116-3"><a href="itsa.html#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">survey.adjust.domain.lonely =</span> <span class="cn">TRUE</span>)</span>
<span id="cb116-4"><a href="itsa.html#cb116-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-5"><a href="itsa.html#cb116-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-6"><a href="itsa.html#cb116-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the survey design</span></span>
<span id="cb116-7"><a href="itsa.html#cb116-7" aria-hidden="true" tabindex="-1"></a>survey_design <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb116-8"><a href="itsa.html#cb116-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">id =</span> <span class="sc">~</span>psu9621,</span>
<span id="cb116-9"><a href="itsa.html#cb116-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">strata =</span> <span class="sc">~</span>stra9621,</span>
<span id="cb116-10"><a href="itsa.html#cb116-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">weights =</span> <span class="sc">~</span>poolwt,</span>
<span id="cb116-11"><a href="itsa.html#cb116-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> pool_data_linked,</span>
<span id="cb116-12"><a href="itsa.html#cb116-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nest =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="descriptive-analysis" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Descriptive analysis<a href="itsa.html#descriptive-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Once that’s done, we can do some descriptive analysis.</p>
<p>Using the <code>svytable</code> function, we can estimate the weighted-sample of males and females in the United States (US). In our MEPS dataset, there are 160,228,773 males and 166,678,038 females, which is representative of the non-institutionalized civilian US population.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="itsa.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>sex, <span class="at">design =</span> survey_design)</span></code></pre></div>
<pre><code>## sex
##           1           2 
## 160228772.9 166678038.1</code></pre>
<p>Moreover, we can look at the survey-weighted total healthcare costs between males and females. For instance, in 2016, the average annual total healthcare costs for males and females were $4351 and $5633 per person, respectively.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="itsa.html#cb119-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>totexp, <span class="sc">~</span>year<span class="sc">+</span>sex, survey_design, svymean)</span>
<span id="cb119-2"><a href="itsa.html#cb119-2" aria-hidden="true" tabindex="-1"></a>df1</span></code></pre></div>
<pre><code>##        year sex      totexp          se
## 2016.1 2016   1 4351.797969 143.3686740
## 2017.1 2017   1 4792.911089 153.9208333
## 2018.1 2018   1 5488.304037 174.0676798
## 2019.1 2019   1 5747.014931 158.7998588
## 2020.1 2020   1 5861.277852 244.1047619
## 2021.1 2021   1 6250.655387 282.9494481
## 2016.2 2016   2 5632.649717 153.3156133
## 2017.2 2017   2 5797.182100 162.3600394
## 2018.2 2018   2 6614.338104 173.1029815
## 2019.2 2019   2 6736.551546 158.9384299
## 2020.2 2020   2 6654.997756 204.6000543
## 2021.2 2021   2 7597.159563 234.2313172</code></pre>
<p>We can also look at the survey-weighted average cost before and after the intervention (before and after 2019). For instance, before the intervention the survey-weighted average total healthcare cost for males and females were $4880 and $6016, respectively. After the intervention, the survey-weighted average total healthcare costs for males and females were $5954 and $6997, respectively.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="itsa.html#cb121-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>totexp, <span class="sc">~</span>sex<span class="sc">+</span>period, survey_design, svymean)</span>
<span id="cb121-2"><a href="itsa.html#cb121-2" aria-hidden="true" tabindex="-1"></a>df2</span></code></pre></div>
<pre><code>##     sex period      totexp          se
## 1.0   1      0 4879.518399 103.6333733
## 2.0   2      0 6016.325527 109.4863008
## 1.1   1      1 5954.493236 166.0967456
## 2.1   2      1 6997.285661 138.6561924</code></pre>
<p>We can visualize the trend of the survey-weighted total healthcare costs for males and females from 2016 to 2021 using the <code>ggsurvey</code> function. From the plot, we can see that the female group had a higher total healthcare cost trend compared to males.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="itsa.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot total expenditures over time (Load the &quot;questionr&quot; package to use &quot;ggsurvey&quot;)</span></span>
<span id="cb123-2"><a href="itsa.html#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvey</span>(survey_design) <span class="sc">+</span></span>
<span id="cb123-3"><a href="itsa.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> totexp, <span class="at">group =</span> <span class="fu">factor</span>(sex), <span class="at">color =</span> <span class="fu">factor</span>(sex)) <span class="sc">+</span></span>
<span id="cb123-4"><a href="itsa.html#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> <span class="st">&quot;mean&quot;</span>, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
</div>
<div id="linear-regression-model" class="section level2 hasAnchor" number="6.6">
<h2><span class="header-section-number">6.6</span> Linear regression model<a href="itsa.html#linear-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can now construct our linear regression model using the ITSA framework. Because we have survey-weights that need to be applied, we will use the <code>svyglm</code> function. We will have several interaction terms according to the ITSA formula presented above. The triple interaction term (<code>factor(period):factor(sex):year</code>) denotes the difference-in-differences estimation. In other words, it is the difference in total healthcare costs between males and females before and after the intervention was implemented. Think of it as subtracting the difference before and after for males and the difference before and after for females. Thus, we are getting two types of differences or the difference-in-differences.</p>
<ul>
<li><p><code>sex</code> denotes our grouping variable</p></li>
<li><p><code>period</code> denotes the binary variable that denotes when the intervention was implemented (<code>0 = before</code>, <code>1 = after</code>)</p></li>
<li><p><code>year</code> denotes the time variable in the model</p></li>
</ul>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="itsa.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ITSA: Triple interaction approach</span></span>
<span id="cb124-2"><a href="itsa.html#cb124-2" aria-hidden="true" tabindex="-1"></a>itsa1 <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(totexp <span class="sc">~</span> <span class="fu">factor</span>(sex) <span class="sc">+</span> <span class="fu">factor</span>(period) <span class="sc">+</span> year <span class="sc">+</span> <span class="fu">factor</span>(period)<span class="sc">:</span><span class="fu">factor</span>(sex) <span class="sc">+</span> <span class="fu">factor</span>(sex)<span class="sc">:</span>year <span class="sc">+</span> <span class="fu">factor</span>(period)<span class="sc">:</span><span class="fu">factor</span>(sex)<span class="sc">:</span>year, <span class="at">design =</span> survey_design) <span class="do">## ITSA linear model</span></span>
<span id="cb124-3"><a href="itsa.html#cb124-3" aria-hidden="true" tabindex="-1"></a>itsa1.confint <span class="ot">&lt;-</span> <span class="fu">confint</span>(itsa1) <span class="do">## generate the 95% CI</span></span>
<span id="cb124-4"><a href="itsa.html#cb124-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-5"><a href="itsa.html#cb124-5" aria-hidden="true" tabindex="-1"></a><span class="co"># &quot;cbind&quot; the coefficient output with 95% CI output</span></span>
<span id="cb124-6"><a href="itsa.html#cb124-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(</span>
<span id="cb124-7"><a href="itsa.html#cb124-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(</span>
<span id="cb124-8"><a href="itsa.html#cb124-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(itsa1, <span class="at">df.resid =</span> <span class="fu">degf</span>(itsa1<span class="sc">$</span>survey.design))<span class="sc">$</span>coef, </span>
<span id="cb124-9"><a href="itsa.html#cb124-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">confint</span>(itsa1, <span class="at">df =</span> <span class="fu">degf</span>(itsa1<span class="sc">$</span>survey.design))</span>
<span id="cb124-10"><a href="itsa.html#cb124-10" aria-hidden="true" tabindex="-1"></a>  ), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                                      Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                       -1141706.66  227313.30   -5.02     0.00
## factor(sex)2                        156608.67  280182.38    0.56     0.58
## factor(period)1                     638235.37  399815.90    1.60     0.11
## year                                   568.46     112.71    5.04     0.00
## factor(sex)2:factor(period)1       -516623.61  486326.52   -1.06     0.29
## factor(sex)2:year                      -77.08     138.92   -0.55     0.58
## factor(sex)1:factor(period)1:year     -316.27     198.07   -1.60     0.11
## factor(sex)2:factor(period)1:year      -60.45     181.29   -0.33     0.74
##                                         2.5 %     97.5 %
## (Intercept)                       -1588358.77 -695054.56
## factor(sex)2                       -393926.88  707144.22
## factor(period)1                    -147370.28 1423841.03
## year                                   347.00     789.92
## factor(sex)2:factor(period)1      -1472215.58  438968.35
## factor(sex)2:year                     -350.04     195.88
## factor(sex)1:factor(period)1:year     -705.47      72.93
## factor(sex)2:factor(period)1:year     -416.68     295.78</code></pre>
</div>
<div id="plot" class="section level2 hasAnchor" number="6.7">
<h2><span class="header-section-number">6.7</span> Plot<a href="itsa.html#plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can plot our ITSA along with the counterfactuals. We create two new objects <code>itsa1</code> and <code>itsa2</code>, which contain the predicted values from our model. The first object <code>itsa1</code> contains the predictive value with all of our terms including the triple interaction. The second object <code>itsa2</code> contains only the counterfactual terms.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="itsa.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb126-2"><a href="itsa.html#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb126-3"><a href="itsa.html#cb126-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb126-4"><a href="itsa.html#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="do">### Plot: Part 1 - Generate the predictions</span></span>
<span id="cb126-5"><a href="itsa.html#cb126-5" aria-hidden="true" tabindex="-1"></a>plot.itsa1 <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(itsa1, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;period&quot;</span>), <span class="at">ci.level =</span> <span class="fl">0.95</span>) <span class="co"># Full model</span></span>
<span id="cb126-6"><a href="itsa.html#cb126-6" aria-hidden="true" tabindex="-1"></a>plot.itsa2 <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(itsa1, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;sex&quot;</span>), <span class="at">ci.level =</span> <span class="fl">0.95</span>) <span class="co"># Counterfactual</span></span>
<span id="cb126-7"><a href="itsa.html#cb126-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-8"><a href="itsa.html#cb126-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-9"><a href="itsa.html#cb126-9" aria-hidden="true" tabindex="-1"></a><span class="do">### Plot: Part 2 - Plot the fitted values</span></span>
<span id="cb126-10"><a href="itsa.html#cb126-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Start with the scatter (average values at each year by group)</span></span>
<span id="cb126-11"><a href="itsa.html#cb126-11" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;navyblue&quot;</span>) <span class="co"># Create color vector</span></span>
<span id="cb126-12"><a href="itsa.html#cb126-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-13"><a href="itsa.html#cb126-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1<span class="sc">$</span>year, df1<span class="sc">$</span>totexp, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">lwd =</span> <span class="dv">1</span>,</span>
<span id="cb126-14"><a href="itsa.html#cb126-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> colors[<span class="fu">factor</span>(df1<span class="sc">$</span>sex)],</span>
<span id="cb126-15"><a href="itsa.html#cb126-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Time (year)&quot;</span>, </span>
<span id="cb126-16"><a href="itsa.html#cb126-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Average total healthcare costs ($)&quot;</span>,</span>
<span id="cb126-17"><a href="itsa.html#cb126-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">4000</span>, <span class="dv">8000</span>))</span>
<span id="cb126-18"><a href="itsa.html#cb126-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Groups&quot;</span>, </span>
<span id="cb126-19"><a href="itsa.html#cb126-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>),</span>
<span id="cb126-20"><a href="itsa.html#cb126-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;navyblue&quot;</span>))</span>
<span id="cb126-21"><a href="itsa.html#cb126-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-22"><a href="itsa.html#cb126-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the lines for the per-post index periods</span></span>
<span id="cb126-23"><a href="itsa.html#cb126-23" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa1, x <span class="sc">&lt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> facet <span class="sc">==</span> <span class="dv">0</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span>
<span id="cb126-24"><a href="itsa.html#cb126-24" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa1, x <span class="sc">&lt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> facet <span class="sc">==</span> <span class="dv">0</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;navyblue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span>
<span id="cb126-25"><a href="itsa.html#cb126-25" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa1, x <span class="sc">&gt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> facet <span class="sc">==</span> <span class="dv">1</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span>
<span id="cb126-26"><a href="itsa.html#cb126-26" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa1, x <span class="sc">&gt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> facet <span class="sc">==</span> <span class="dv">1</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;navyblue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span>
<span id="cb126-27"><a href="itsa.html#cb126-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-28"><a href="itsa.html#cb126-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Line for the index period</span></span>
<span id="cb126-29"><a href="itsa.html#cb126-29" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">2019</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb126-30"><a href="itsa.html#cb126-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-31"><a href="itsa.html#cb126-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual lines</span></span>
<span id="cb126-32"><a href="itsa.html#cb126-32" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa2, x <span class="sc">&gt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">1</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span>
<span id="cb126-33"><a href="itsa.html#cb126-33" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(plot.itsa2, x <span class="sc">&gt;=</span> <span class="dv">2019</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">2</span>), <span class="fu">lines</span>(x, predicted, <span class="at">col =</span> <span class="st">&quot;navyblue&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
</div>
<div id="parallel-trends-assumption" class="section level2 hasAnchor" number="6.8">
<h2><span class="header-section-number">6.8</span> Parallel trends assumption<a href="itsa.html#parallel-trends-assumption" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The most critical part of the ITSA results are the parallel trends assumption and the difference-in-differences estimator.</p>
<p>Let’s start with the parallel trends assumption. We need to test to see if the trends between males and females are similar <u>before</u> the implementation of the intervention, which we can find in our model output. Based on our findings (see <code>factor(sex)2:year</code> coefficient), the slopes between the two groups (males and females) before the intervention were not statistically different (average difference = -$77 (95% CI: -$350, $196). This means that the slopes are not significantly different between males and females. See ITSA Figure below with annotations.</p>
<p>Once we are confident that the trends prior to the implementation of the intervention are not different, any changes we see after the intervention can be attributed to the intervention. This is an important condition for the difference-in-differences design.</p>
</div>
<div id="additional-estimations" class="section level2 hasAnchor" number="6.9">
<h2><span class="header-section-number">6.9</span> Additional estimations<a href="itsa.html#additional-estimations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can use the <code>margins</code> command to estimate the partial derivatives of the total healthcare costs along different parts of the timeline.</p>
<p>For instance, the average difference in total healthcare costs for males and females <u>before</u> and <u>after</u> the intervention were $1020 and $777, respectively. I’ve summarized these results into a table below.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="itsa.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Average difference total costs in the pre- and post-intervention periods. </span></span>
<span id="cb127-2"><a href="itsa.html#cb127-2" aria-hidden="true" tabindex="-1"></a>margins1 <span class="ot">&lt;-</span> <span class="fu">margins</span>(itsa1, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">design =</span> survey_design, <span class="at">at =</span> (<span class="fu">list</span>(<span class="at">period =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>)), <span class="at">variables =</span> <span class="st">&quot;sex&quot;</span>)</span>
<span id="cb127-3"><a href="itsa.html#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(margins1)</span></code></pre></div>
<pre><code>##  factor period       AME       SE      z      p    lower     upper
##    sex2 0.0000 1020.3870 251.0666 4.0642 0.0000 539.0557 1523.2188
##    sex2 1.0000  777.3969 260.7194 2.9817 0.0029 241.4676 1263.4687</code></pre>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-91"></span>
<img src="Figure%206_2.png" alt="Differences in total healthcare costs between males and females." width="100%" />
<p class="caption">
Figure 6.2: Differences in total healthcare costs between males and females.
</p>
</div>
<p>We could also estimate the slopes or the average annual change in the total healthcare costs for males and females <u>after</u> the intervention using the <code>margins</code> commands. For instance, average annual change in total healthcare costs for males and females are $252 and $431, respectively.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="itsa.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Slopes after the intervention</span></span>
<span id="cb129-2"><a href="itsa.html#cb129-2" aria-hidden="true" tabindex="-1"></a>margins3 <span class="ot">&lt;-</span> <span class="fu">margins</span>(itsa1, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>, <span class="at">design =</span> survey_design, <span class="at">at =</span> (<span class="fu">list</span>(<span class="at">period =</span> <span class="dv">1</span>, <span class="at">sex =</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>))), <span class="at">variables =</span> <span class="st">&quot;year&quot;</span>)</span>
<span id="cb129-3"><a href="itsa.html#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(margins3)</span></code></pre></div>
<pre><code>##  factor period    sex      AME       SE      z      p    lower    upper
##    year 1.0000 1.0000 252.1903 151.9225 1.6600 0.0969 -45.5724 549.9530
##    year 1.0000 2.0000 430.9319 134.2015 3.2111 0.0013 167.9019 693.9620</code></pre>
</div>
<div id="issues-with-the-current-model" class="section level2 hasAnchor" number="6.10">
<h2><span class="header-section-number">6.10</span> Issues with the current model<a href="itsa.html#issues-with-the-current-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>However, it is not possible to compare the slopes using the <code>R</code> version of the <code>margins</code> package. I have tried to search for a way to do this, but the <code>margins</code> package for <code>R</code> currently can’t perform this comparison. You can follow the discussion on the <code>margins</code> GitHub page (<a href="https://github.com/leeper/margins/issues/124">link</a>), which discusses some potential solution. However, I prefer to use <code>Stata</code> for these comparisons. Fortunately, there is a way to make some important conclusions using a different method–the <u>linear spline model</u>.</p>
</div>
<div id="workaround-using-a-linear-spline-model" class="section level2 hasAnchor" number="6.11">
<h2><span class="header-section-number">6.11</span> Workaround using a linear spline model<a href="itsa.html#workaround-using-a-linear-spline-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We could get the difference in the level change <u>immediately after</u> implementation of the intervention at <code>year == 2019</code> using the <code>lspline</code> command. We can also get the difference-in-differences estimate with this approach.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="itsa.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ITSA: Linear splines approach</span></span>
<span id="cb131-2"><a href="itsa.html#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Create a knot at 2019</span></span>
<span id="cb131-3"><a href="itsa.html#cb131-3" aria-hidden="true" tabindex="-1"></a>spline1 <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(totexp <span class="sc">~</span> <span class="fu">factor</span>(sex) <span class="sc">+</span> <span class="fu">factor</span>(period) <span class="sc">+</span> <span class="fu">lspline</span>(year, <span class="fu">c</span>(<span class="dv">2019</span>), <span class="at">marginal =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">factor</span>(sex)<span class="sc">:</span><span class="fu">lspline</span>(year, <span class="fu">c</span>(<span class="dv">2019</span>), <span class="at">marginal =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">factor</span>(sex)<span class="sc">:</span><span class="fu">factor</span>(period), <span class="at">design =</span> survey_design)</span>
<span id="cb131-4"><a href="itsa.html#cb131-4" aria-hidden="true" tabindex="-1"></a>spline1.confint <span class="ot">&lt;-</span> <span class="fu">confint</span>(spline1)</span>
<span id="cb131-5"><a href="itsa.html#cb131-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-6"><a href="itsa.html#cb131-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Output with 95% CI</span></span>
<span id="cb131-7"><a href="itsa.html#cb131-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(</span>
<span id="cb131-8"><a href="itsa.html#cb131-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(</span>
<span id="cb131-9"><a href="itsa.html#cb131-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(spline1, <span class="at">df.resid =</span> <span class="fu">degf</span>(spline1<span class="sc">$</span>survey.design))<span class="sc">$</span>coef, </span>
<span id="cb131-10"><a href="itsa.html#cb131-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">confint</span>(spline1, <span class="at">df =</span> <span class="fu">degf</span>(spline1<span class="sc">$</span>survey.design))</span>
<span id="cb131-11"><a href="itsa.html#cb131-11" aria-hidden="true" tabindex="-1"></a>  ), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                                                          Estimate Std. Error
## (Intercept)                                           -1141706.66  227313.30
## factor(sex)2                                            156608.67  280182.38
## factor(period)1                                           -313.65     285.65
## lspline(year, c(2019), marginal = TRUE)1                   568.46     112.71
## lspline(year, c(2019), marginal = TRUE)2                  -316.27     198.07
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)1      -77.08     138.92
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)2      255.82     240.93
## factor(sex)2:factor(period)1                              -118.53     370.05
##                                                       t value Pr(&gt;|t|)
## (Intercept)                                             -5.02     0.00
## factor(sex)2                                             0.56     0.58
## factor(period)1                                         -1.10     0.27
## lspline(year, c(2019), marginal = TRUE)1                 5.04     0.00
## lspline(year, c(2019), marginal = TRUE)2                -1.60     0.11
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)1   -0.55     0.58
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)2    1.06     0.29
## factor(sex)2:factor(period)1                            -0.32     0.75
##                                                             2.5 %     97.5 %
## (Intercept)                                           -1588358.77 -695054.56
## factor(sex)2                                           -393926.88  707144.22
## factor(period)1                                           -874.93     247.63
## lspline(year, c(2019), marginal = TRUE)1                   347.00     789.92
## lspline(year, c(2019), marginal = TRUE)2                  -705.47      72.93
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)1     -350.04     195.88
## factor(sex)2:lspline(year, c(2019), marginal = TRUE)2     -217.59     729.23
## factor(sex)2:factor(period)1                              -845.64     608.58</code></pre>
<p>The linear spline model creates <code>knots</code> that automatically replaces some of the interactions in our previous model. For example the model element <code>factor(sex):lspline(year, c(2019)</code> replaces the triple interaction <code>factor(period):factor(sex):year</code> from our previous model.</p>
<p>You’ll notice that some of the coefficient values are similar to our first model. For instance, in our first model, the <code>year</code> coefficient was equal to $568, and in the linear splines model, the <code>lspline(year, c(2019), marginal = TRUE)1</code> coefficient was equal to $568. This denotes the average change in annual total healthcare costs for males before the implementation of the intervention at <code>year == 2019</code>.</p>
<p>However, you’ll also notice some differences. In the linear splines model, we have a couple of important coefficients that will help to complete our evaluation of the ITSA model.</p>
</div>
<div id="differences-in-level-immediately-after-implementation-of-the-intervention" class="section level2 hasAnchor" number="6.12">
<h2><span class="header-section-number">6.12</span> Differences in level immediately after implementation of the intervention<a href="itsa.html#differences-in-level-immediately-after-implementation-of-the-intervention" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the most important changes we are interested in is the <em>immediate</em> change after implementation of the intervention at <code>year == 2019</code>. This is captured with the <code>factor(sex)2:factor(period)1</code> coefficient, which has a value equal to -$119 (95% CI: -$846, $609). This tells me that the difference in level change at <code>year == 2019</code> was lower for females than males; however, this difference was not statistically significant. See ITSA Figure below with annotations.</p>
</div>
<div id="difference-in-differences-estimation" class="section level2 hasAnchor" number="6.13">
<h2><span class="header-section-number">6.13</span> Difference-in-differences estimation<a href="itsa.html#difference-in-differences-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Lastly, we can identify the difference-in-differences estimate from the linear spline model output in the form of the <code>factor(sex)2:lspline(year, c(2019), marginal = TRUE)2</code> coefficient, which has a value equal to $256 (95% CI: -$218, $729). This coefficient denotes that average annual change in total healthcare expenditure between males and females before and after implementation of the intervention. In other words, this is a difference in the slopes for males before and after the intervention minus the difference in the slopes for females before and after the intervention. Hence, the term <code>difference-in-differences</code>. See ITSA Figure below with annotations.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-94"></span>
<img src="Figure%206_3.png" alt="ITSA figure with annotations." width="100%" />
<p class="caption">
Figure 6.3: ITSA figure with annotations.
</p>
</div>
</div>
<div id="putting-it-all-together" class="section level2 hasAnchor" number="6.14">
<h2><span class="header-section-number">6.14</span> Putting it all together<a href="itsa.html#putting-it-all-together" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With the ITSA, we will summarize our findings into a table. These include the main coefficients from the ITSA model.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-95"></span>
<img src="Figure%206_4.png" alt="Summary table for main ITSA coefficients." width="100%" />
<p class="caption">
Figure 6.4: Summary table for main ITSA coefficients.
</p>
</div>
</div>
<div id="conclusions-5" class="section level2 hasAnchor" number="6.15">
<h2><span class="header-section-number">6.15</span> Conclusions<a href="itsa.html#conclusions-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The ITSA model is a very useful design to generate causal interpretation as long as the assumptions hold. For instance, the parallel trends assumptions needs to be assessed. Without it, it will be difficult to argue that the intervention was the only factor that could have impacted the changes in the level and trends between the groups.</p>
<p>In this tutorial, I ran into an issue with the first ITSA model using interaction terms. It didn’t provide me with the necessary coefficients to determine the main coefficients for the ITSA. For instance, I had to use a linear spline model to identify the difference-in-differences estimate. Although the ITSA model with the triple interaction was useful in generating the plot, I could have started with the linear splines model and generated the ITSA plot afterwards with the triple interaction model.</p>
<p>At the end of the day, I was able to generate a summary table and a very nice figure of the ITSA. However, I will continue to learn more about other contrasting packages such as <a href="https://github.com/rvlenth/emmeans"><code>emmeans</code></a> and <a href="https://github.com/vincentarelbundock/marginaleffects"><code>marginaleffects</code></a>.</p>
<p>Although the <code>margins</code> package in <code>R</code> doesn’t have the <code>pwcompare</code> feature from <code>Stata</code>, there are some potential workarounds that I’ll investigate further. Discussion about this can be found in the <code>margins</code> GitHub issues forum (<a href="https://github.com/leeper/margins/issues/124">link</a>)</p>
</div>
<div id="acknowledgements-5" class="section level2 hasAnchor" number="6.16">
<h2><span class="header-section-number">6.16</span> Acknowledgements<a href="itsa.html#acknowledgements-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As always, I am grateful to the <code>R</code> community for producing wonderful tools for novices like me. I’ve learned so much reading documents, forums, and issues online that it would be impossible to credit everyone. But I would like to highlight a few superstars that I think deserve special recognition.</p>
<p>I am grateful to the author of the <code>margins</code> package, Thomas J. Leeper. You can find his <code>margins</code> package on his <a href="https://github.com/leeper/margins"><code>GitHub site</code></a>.</p>
<p>Additionally, the <code>marginaleffects</code> package by Vincent Arel-Bundock has helped me to compare some of <code>R</code>’s marginal effects commands with <code>Stata</code>. You can find his GitHub site <a href="https://github.com/vincentarelbundock/marginaleffects">here</a>.</p>
<p>The <code>emmeans</code> package was developed by Russel V. Length, which I plan on learning more about on his GitHub site (<a href="https://github.com/rvlenth/emmeans">link</a>). Note: I found a nice overview of the <code>emmeans</code> package by Ariel Muldoon that I encourage interested users to read (<a href="https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/">link</a>).</p>
<p>The <code>ggeffect</code> package was very useful in helping me develop some very nice plots, which you can learn more about on their GitHub site (<a href="https://strengejacke.github.io/ggeffects/">link</a>).</p>
<p>Lastly, I found this amazing site on ITSA by Chrissy H. Roberts <a href="https://rpubs.com/chrissyhroberts/1006858">here</a>. Her site helped me to create the ITSA plot which is in this tutorial. I hope you get a chance to read her blog on how to conduct an ITSA in R. I think she does a much better job that I did with this tutorial.</p>
</div>
<div id="work-in-progress-2" class="section level2 hasAnchor" number="6.17">
<h2><span class="header-section-number">6.17</span> Work in progress<a href="itsa.html#work-in-progress-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is a work in progress so expect some updates in the future.</p>
</div>
<div id="disclaimers-2" class="section level2 hasAnchor" number="6.18">
<h2><span class="header-section-number">6.18</span> Disclaimers<a href="itsa.html#disclaimers-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Any errors or mistakes are those of the author.</p>
<p>This is only for educational purposes.</p>
<p>This was built under R version 4.3.1 “Beagle Scouts”</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="trends.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="notes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-linearsplines.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
